- README.md
> additional security related notes

- .github/SUPPORT.md
> support.md typos

- package.json
> fix #155 Make command titles conform to VS Code style

- .prettierrc
> fix #160 linebreak problems reported on every source line on Windows

- .vscode/launch.json
- webpack.config.js
> fix #169 webpack before launch, and use correct outFiles

- src/providers/ObjectScriptDiagnosticProvider.ts
> Added diagnostic to warn if non-latin characters found in class elements

- src/commands/studio.ts
> reject progress if error in studio actions happens

- src/api/index.ts
- src/debug/debugAdapterFactory.ts
- src/debug/debugSession.ts
resolves: #144 
resolves: #143 
resolves: #137
> debugging improvements

- .vscode/extensions.json
> Move extensions.json out of PR #183

- src/providers/ObjectScriptDiagnosticProvider.ts
Updated diagnostics
Resolves: #48
> Underline as an error member`s names which contains not valid characters, class without package

- src/api/atelier.d.ts
- src/api/index.ts
- src/commands/compile.ts
- src/commands/export.ts
- src/commands/studio.ts
- src/extension.ts
- src/providers/FileSystemPovider/FileSystemProvider.ts
- src/utils/index.ts
> Respect changes on server

- src/providers/ObjectScriptCompletionItemProvider.ts
Just type any macros name without `$$$` prefix, and it should offer to replace it with prefix `$$$`
Unfortunately, AtelierAPI returns a very limited list of macroses names, so, it does not support a full list of available macroses in the current document.
Previous behavior still works
resolves: #96
> suggest macros name without $$$ prefix

- package.json
- src/utils/index.ts
> added ability to define env-file if docker-compose used

- src/commands/export.ts
> Export from another namespace, message updated

- src/providers/ObjectScriptDiagnosticProvider.ts
> fix for wrong diagnostic error in class names

- package.json
- src/commands/compile.ts
- src/extension.ts
> Import folder only, without compilation from files explorer

- src/commands/serverActions.ts
> fix for custom links in server menu

- src/commands/compile.ts
- src/providers/FileSystemPovider/FileSystemProvider.ts
> better update for last modified time, by any import to server

- src/explorer/explorer.ts
> fix #162 pass folder name to ObjectScript Explorer root node

- src/utils/index.ts
> skip compilation for local CSP files, yet, for now

- src/providers/FileSystemPovider/FileSystemProvider.ts
> fix for creating new files on isfs

- src/commands/studio.ts
> fix #239 'Studio Action "Changed Namespace" not supported' in Output

- CHANGELOG.md
@daimor this assumes you will approve and merge #238 and #242.
After that has been done, please approve this one and merge it. Then release 0.8.8.
> Changelog for 0.8.8

- src/api/index.ts
> fix #247 Handle non-isfs multi-server multiroot in OE

- src/commands/studio.ts
- src/extension.ts
> fix #251 'Studio Action "Changed Namespace" not supported'

- src/commands/compile.ts
- src/providers/FileSystemPovider/FileSystemProvider.ts
> fix #250 Get isfs saving to work again

- src/commands/studio.ts
Open Studio Extension CSP pages without a progress bar in the lower right.
> Open CSP pages and improve AfterUserAction

- package-lock.json
- package.json
Resolved by running `npm audit fix`
> Resolve dependabot alert about serialize-javascript

- src/commands/export.ts
> fixes in configuration export.addCategory

- .github/workflows/main.yml
- src/api/index.ts
- src/providers/FileSystemPovider/TextSearchProvider.ts
> fix #269 Server-side search of isfs folder using proposed API failed when using Server Manager connection

- package.json
- src/extension.ts
> fix #256 reload file explorer after connection

- src/commands/compile.ts
- src/extension.ts
- src/providers/FileSystemPovider/FileSystemProvider.ts
> Fix 276 Refresh from server correctly after isfs save and compile

- package.json
> fix #278 Exclude some commands from Command Palette

- src/commands/compile.ts
> fix #279 Ctrl+F7 (Import and Compile Current File) was broken

- .github/pull_request_template.md
> fix #288 add a PR template for GitHub

- .github/workflows/main.yml
fixed branch for testing
changed vsix file in artifacts
ignore marketplace if no token provided
Fixes: #290
> Some changes and fixes in workflow

- docs/Configuration.md
- docs/Installation.md
- docs/RunDebug.md
- docs/ServerSide.md
- docs/Settings.md
- docs/index.md
- docs/workspace.md
> paths and images work

- .github/workflows/main.yml
> fix beta releases

- src/extension.ts
This PR is to trigger a new beta build following #290 v2 fix
> Push comment-only change to trigger new beta build now #290 is merged

- README.md
with the publisher id changed, this is necessary
> fix links to shields

- src/commands/studio.ts
> Launching CSP pages with server manager settings

- src/commands/compile.ts
> fix #282 Don't clear cached mtime too soon during import

- LICENSE
> adding ISC to copyright

- src/providers/FileSystemPovider/FileSystemProvider.ts
> fix #303 flush isfs cache on import and compile

- src/extension.ts
> fix #316 correct routine names on status bar, and extend from INTs to MACs

- CHANGELOG.md
- README.md
CHANGELOG for 0.9.1 plus polishing in README.
> Release 0.9.1

- docs/Configuration.md
> fix #319 remove doc reference to relocated servermanager commands

- README.md
- docs/Configuration.md
- docs/RunDebug.md
- docs/ServerSide.md
- package-lock.json
- package.json
- src/commands/addServerNamespaceToWorkspace.ts
- src/extension.ts
This draft PR fixes #321.
If you like it I will update the documentation to cover it and remove Draft status.
> Implement #321 - Contribute to empty Explorer content

- src/commands/addServerNamespaceToWorkspace.ts
- src/extension.ts
This PR fixes #328, improving the new "Choose Server and Namespace" quickstart feature.
> fix #328 resolve the server spec fully, including credentials

- src/commands/studio.ts
- src/utils/index.ts
> Fix #347: Pass CSP path for CSP files

- src/providers/ObjectScriptClassFoldingRangeProvider.ts
- src/providers/ObjectScriptHoverProvider.ts
> fix #353 Correct a spelling mistake in hover link

- package.json
- src/commands/jumpToTagAndOffset.ts
> Added warning message to Jump to Tag and Offset

- src/commands/subclass.ts
- src/commands/superclass.ts
- src/commands/viewOthers.ts
- src/utils/classDefinition.ts
> fix #355 fix some commands that were broken for isfs files

- src/api/index.ts
- src/debug/debugSession.ts
- src/extension.ts
> fixed, issue with no file exist, correct using sessions

- src/providers/ObjectScriptRoutineSymbolProvider.ts
> Ignore first line of routine for outline and breadcrumb

- src/providers/WorkspaceSymbolProvider.ts
- src/utils/classDefinition.ts
> Make WorkspaceSymbolProvider work with isfs

- CHANGELOG.md
This PR contains README updates for the 0.9.3 release.
> Prepare 0.9.3 release

- src/extension.ts
> Optional SymbolProvider by LanguageServer

- README.md
Use the InterSystems registration mark and fix the README title
> Use the InterSystems registration mark

- src/commands/addServerNamespaceToWorkspace.ts
This PR fixes #389 
The folder uris it creates for webapp access require #384 to have been merged, otherwise they will expand empty.
> fix #389 Support adding of webapp-type workspace folders

- src/api/index.ts
- src/commands/addServerNamespaceToWorkspace.ts
> fix #392 no longer require %SYS namespace access for 'Add Server Namespace to Workspace' command

- src/api/index.ts
> uppercase namespace in API

- src/api/index.ts
> fix issue with toUpperCase

- src/api/index.ts
> fix if no namespace used

- src/extension.ts
@gjsjohnmurray I need a better message for the prompt
> added prompt to install language-server extension

- .github/workflows/main.yml
- Resolves the issue with draft releases
- Publish prebuild package 
- changes in artifacts
> Different fixes in CI

- package.json
- src/commands/export.ts
- src/extension.ts
- src/providers/DocumentContentProvider.ts
> Ability to add file mapping

- src/extension.ts
> install language server extension in the background

- src/api/index.ts
- src/extension.ts
> fix #415 use less statusbar space

- src/explorer/models/workspaceNode.ts
This PR fixes #422 
See that issue for before and after screenshots.
> fix #422 add icons to first-level subfolders of ObjectScript Explorer

- src/api/index.ts
> attempt to solve issue with cookies

- .github/workflows/main.yml
> ci fix for enableProposedApi

- src/commands/addServerNamespaceToWorkspace.ts
- src/commands/connectFolderToServerNamespace.ts
> fix #432 avoid second prompt for username when getting namespace list

- src/extension.ts
> fix #434 wait for connection checks during activation

- src/commands/serverActions.ts
- src/extension.ts
> fix #436 status bar panel behaviour when no connection defined

- .github/workflows/main.yml
> open-vsx publish fixed

- src/debug/debugConfProvider.ts
- src/extension.ts
> fix #445 supply process picker default for processId

- src/utils/index.ts
> fix #447 bad folder name for server-side .vscode storage

- src/commands/addServerNamespaceToWorkspace.ts
> fix #451 add 'lock' codicon prefix to isfs-readonly picks

- src/api/index.ts
Also protect against potential authentication issue during concurrent connection setup.
This PR fixes #458 which was apparently caused by #427
> fix #458 fix authentication after password prompt

- src/extension.ts
This PR fixes #455 
Benefits are only seen when running with proposed APIs enabled.
> fix #455 register ResourceLabelFormatter for isfs (proposed API)

- src/commands/connectFolderToServerNamespace.ts
> fix #460 don't copy user-lever objectscript.conn properties into folder's settings.json

- src/extension.ts
> fix #473 defer to LS 1.0.5+ for FoldingRangeProvider

- src/api/index.ts
> fix #469 error message on failed AtelierAPI.request

- README.md
> fix #478 update README to cover download of beta VSIX for proposed API usage

- src/api/index.ts
- src/commands/serverActions.ts
- src/explorer/explorer.ts
- src/explorer/models/nodeBase.ts
- src/explorer/models/workspaceNode.ts
- src/extension.ts
- src/providers/FileSystemPovider/TextSearchProvider.ts
- src/utils/index.ts
> correct work status bar with docker

- snippets/objectscript-class.json
- snippets/objectscript.json
This PR improves some snippets and adds some new ones. The details are in the two commits.
> Solon snippets

- src/debug/debugSession.ts
> Fixed show of changed variable during debugging

- src/providers/FileSystemPovider/FileSystemProvider.ts
> fix #508 create clickable urls in BPL and DTL documents opened from server

- src/commands/compile.ts
- src/providers/FileSystemPovider/FileSystemProvider.ts
> fix #382 do not overwrite a deployed class

- src/providers/FileSystemPovider/File.ts
- src/providers/FileSystemPovider/FileSystemProvider.ts
> fix #394 don't mangle binary files

- snippets/objectscript-class.json
- snippets/objectscript.json
This PR add Request and Response message type to snippet.
Also, add Snippet shortcut to Class for Class Request/Response/Operation/Service/Production
Add TryCatch snippet and ThrowOnError
> Add Request and Response to snippet

- src/test/runTest.ts
- src/test/suite/extension.test.ts
> Added install extensions for tests

- src/debug/debugSession.ts
- src/debug/xdebugConnection.ts
- src/providers/ObjectScriptClassCodeLensProvider.ts
- src/utils/index.ts
> fixed issues with debugging on isfs

- snippets/objectscript-class.json
> Add snippets from Projection and XData

- package.json
> downgraded engine version requirements for katacoda

- src/commands/addServerNamespaceToWorkspace.ts
> fix #554 use new server:namespace notation for isfs folders added by command

- src/debug/debugSession.ts
> mapped local,global to private,public

- package.json
This PR fixes #532 
I added a link to the documentation on compile flags and qualifiers.
> Update compileFlags setting description

- docs/ServerSide.md
> add John fixes from pr 618 convo

- README.md
- src/providers/FileSystemProvider/FileSystemProvider.ts
> fix #623 recognize 'system=1' isfs queryparam as a signal to include %-items

- snippets/objectscript-class.json
This PR add snippets for business process (both BPL based and code based).
It creates an empty (harmless disabled <trace> activity) BML diagram.
After this, programmer is free to go to management portal to edit the diagram (without opening Studio).
> add snippet for business process

- src/api/index.ts
> fix #535 import into the correct namespace

- src/utils/index.ts
> fix #613 handle spurious whitespace before Class keyword

- src/commands/jumpToTagAndOffset.ts
This PR fixes #368
Updated the Jump to Tag + Offset command to use the DocumentSymbolProvider to get the location of labels.
> Update Jump to Tag + Offset to use DocumentSymbolProvider

- src/extension.ts
> accept empty response for arguments list in debug this method

- src/commands/viewOthers.ts
This PR fixes #645 and fixes #646 
I've exempted non-ObjectScript methods and methods in cached query classes from the new functionality introduced by #632
> 'View Other' fixes

- src/api/index.ts
- src/extension.ts
This PR fixes #608
Also fixes some intermittent superfluous prompting for credentials during connection checking.
> fix #608 update connections when settings are changed

- docs/Configuration.md
- docs/ExtensionUI.md
> Rewrite pre suggestions from John Murray

- docs/Configuration.md
- docs/ExtensionUI.md
- docs/ServerSide.md
This PR makes further updates from John Murray
> Edits per comments from John Murray

- package-lock.json
- package.json
- src/extension.ts
> fix security issues

- src/api/index.ts
- src/commands/compile.ts
> Improve compilation error handling

- package.json
> Allow extension in untrusted workspaces

- src/commands/addServerNamespaceToWorkspace.ts
> fix #682 always run isfs dialog's serverInfo request in %SYS

- src/utils/index.ts
> fix #693 handle startup case where current file is not in any root of the workspace

- src/providers/FileSystemProvider/FileSystemProvider.ts
> Improve handling of scenario where user has insufficient privileges

- src/commands/compile.ts
> Require confirmation for namespace compile command

- src/utils/index.ts
> Allow multiple spaces between Class and name when extracting class from document

- src/providers/FileSystemProvider/FileSystemProvider.ts
This PR fixes #410 
This fix will prevent users from saving changes to the wrong class (see step 6 in #410). However, the new stub class (step 5) will still be created. This can't be prevented because the `Save As` creates the file with empty `content` before overwriting that empty content with the contents of the original file instead of creating the new class with the `content` from the original class.
> Block save of `isfs` classes where the class name and file name don't match

- src/commands/export.ts
> Refresh ObjectScript Explorer after export

- src/languageConfiguration.ts
> Add auto-commenting of new lines following existing ObjectScript comments

- CHANGELOG.md
- README.md
- package.json
This PR prepares for the 1.1.0 release.
> 1.1.0 - update README and CHANGELOG, bump minor version

- src/debug/xdebugConnection.ts
> Check for undefined `hitCondition`

- src/commands/studio.ts
This PR makes it easier to diagnose issues like #781
> Improve error messaging for Studio Actions

- .github/workflows/main.yml
> failed on windows

- package-lock.json
- package.json
updated node-fetch caused the issue, downgraded back to working version
This PR fixes #791
> downgrade node-fetch

- README.md
> Update `Enable Proposed APIs` steps

- .github/workflows/main.yml
- package.json
> fix releasing in ci

- .github/workflows/main.yml
> Next attempt for CI, install packages then remove proposals

- src/debug/debugSession.ts
This PR fixes #804
I used a modified version of the code from `viewOthers()` that uses our `DocumentSymbolProvider` to determine what method we're in and how long its definition is
> Properly map method offsets when debugging a class with multiline method arguments

- CHANGELOG.md
- README.md
- src/extension.ts
This PR fixes #827
I will do a release once this PR is merged.
> Fix Proposed API checks

- .github/workflows/prerelease.yml
This PR adds a new yml file to implement CI for the prerelease branch, It is derived from the one for the main branch.
> Add CI for prerelease branch

- src/providers/FileSystemProvider/FileSearchProvider.ts
> Have `FileSearchProvider` use `DocumentContentProvider.getUri()` to generate URIs

- src/commands/compile.ts
- src/utils/index.ts
This PR fixes #858 and fixes #859
> Fix issues with `compileFolder` and `importFolder` commands

- src/api/index.ts
- src/providers/FileSystemProvider/FileSystemProvider.ts
> support isfs copy

- src/extension.ts
- src/providers/FileSystemProvider/FileSystemProvider.ts
> Generate content when a new local class or routine is created

- docs/ServerSide.md
> Improve docs for isfs `filter` param

- src/utils/index.ts
> Fix syncing of local CSP files

- src/api/index.ts
> Use `response.arrayBuffer()` instead of `buffer()`

- src/api/index.ts
> Give `docker-compose` setting priority over `server` one (fix #898)

- docs/SettingsReference.md
- package.json
- src/extension.ts
See https://github.com/intersystems-community/vscode-objectscript/issues/876#issuecomment-1077333926
> Improve `objectscript.openClassContracted` setting

- docs/SettingsReference.md
- package.json
- src/commands/export.ts
> Add `objectscript.export.exactFilter` setting

- src/api/index.ts
- src/commands/delete.ts
- src/providers/FileSystemProvider/FileSystemProvider.ts
This PR adds the ability to delete all the contents of a package or web app folder. We can consider closing #854 since this fixes one of the holes in #857.
> Implement `isfs` package/folder deletion

- README.md
> Nudge people to install the extension pack first

- docs/ServerSide.md
- docs/SettingsReference.md
- package.json
- src/commands/export.ts
- src/utils/FileProviderUtil.ts
> Add `mapped` options for isfs and export

- src/extension.ts
> Strip export folder with subfolders for new local class content generation

- src/utils/index.ts
> Fix getting host port number for connection to docker-compose with multiple services

- docs/SettingsReference.md
- docs/_sass/color_schemes/isc.scss
Add some documentation of objectscript.conn settings, including the very useful docker-compose object
> add some settings doc

- src/commands/compile.ts
- src/extension.ts
- src/utils/index.ts
> Improve importing logic

- docs/SettingsReference.md
This new formatting setting will be applicable for the next LS version, which I will release early this week.
> Document new Language Server setting

- docs/RunDebug.md
- src/extension.ts
> Use open document's server for `attach` debug sessions

- src/extension.ts
Six of our event handlers weren't being properly disposed of when the extension deactivated.
> Properly dispose of all event handlers

- package-lock.json
- package.json
- src/test/runTest.ts
Using guidance from https://github.com/microsoft/vscode-discussions/discussions/43#discussioncomment-3334936
> Fix macOS build error

- .github/workflows/main.yml
This PR attempts to fix #625
It also reduces the Open VSX upload timeout from 15 minutes to 5
> Try using `concurrency` to fix #625

- docs/Configuration.md
Arose from https://community.intersystems.com/post/vs-code-connection-using-prefix
> Document the `pathPrefix` property of the `webServer` object

- docs/SettingsReference.md
- package.json
- src/extension.ts
> Add `objectscript.importOnSave` setting

- src/commands/export.ts
> Improve export error logging

- src/api/index.ts
- src/commands/serverActions.ts
- src/extension.ts
> Skip triggering refreshes at end of some checkConnection calls

- src/commands/export.ts
- src/extension.ts
- src/providers/DocumentContentProvider.ts
- src/utils/index.ts
> Fix uncaught errors reported when no workspace is open

- package-lock.json
- package.json
>  Hide `-injection` languages from selector (#1010) 

- src/providers/FileSystemProvider/TextSearchProvider.ts
> Properly report matches in Storage definitions

- src/debug/debugSession.ts
> Fix debug breakpoint mapping when Language Server is absent

- .github/workflows/codeql-analysis.yml
- .github/workflows/main.yml
- .github/workflows/prerelease.yml
This PR fixes #1020 
@daimor @gjsjohnmurray What's the best way to test actions? The changes I made should be pretty straightforward but some extra testing wouldn't hurt.
> Resolve GitHub Actions deprecation warnings

- src/commands/serverActions.ts
> add ? to url if not present before adding token

- src/commands/export.ts
This PR fixes #1058
It also corrects a bug in how binary file export was being handled when the `export.dontExportIfNoChanges` setting was `true`. The export only happened if the contents **were** identical.
Testing that change revealed that **import** of a binary file (e.g. a web app's image file) is broken, corrupting the server copy of the file. I will open a separate issue for this.
> Update local workspace mtime record when exporting (fixes #1058)

- package-lock.json
- package.json
- src/commands/compile.ts
- src/explorer/explorer.ts
- src/providers/DocumentContentProvider.ts
- src/providers/ObjectScriptDefinitionProvider.ts
- src/utils/index.ts
> Fix import of binary files such as webapp images (#1060)

- src/utils/index.ts
> Fix deployed check

- src/providers/FileSystemProvider/FileSystemProvider.ts
> Fix isfs folder deletion

- src/utils/index.ts
> Fall back to Index for deployed check if query fails

- src/debug/debugSession.ts
> Correctly set breakpoints in methods with quoted names

- src/commands/project.ts
- src/explorer/explorer.ts
- src/utils/FileProviderUtil.ts
> Properly handle other files and packages in server-side projects

- src/api/index.ts
- src/commands/addServerNamespaceToWorkspace.ts
- src/commands/connectFolderToServerNamespace.ts
> Fix namespace pick when trying to connect without permissions on `%SYS`

- src/providers/FileSystemProvider/TextSearchProvider.ts
> Fix server-side search in compiler keywords and values

- src/api/index.ts
> Fix api version check in AtelierAPI.getDoc()

- snippets/objectscript-class.json
> Add snippet for custom class queries

- docs/SettingsReference.md
> Additional documentation for `objectscript.export` settings

- src/commands/compile.ts
- src/providers/DocumentContentProvider.ts
- src/providers/FileSystemProvider/FileSystemProvider.ts
- src/utils/index.ts
This PR implements changes required by the upcoming testing manager extension.
> For testingmanager

- src/utils/index.ts
> Fix launching Docker shell or terminal on Windows

- src/extension.ts
This PR applies my suggestions from PR #1089
> Update error handling for #1089

- docs/Configuration.md
- src/commands/serverActions.ts
> Support a ${project} variable in Server Actions Menu custom entries

- src/commands/delete.ts
> Always prompt for confirmation when deleting from ObjectScript Explorer

- package-lock.json
> Force new beta

- docs/Configuration.md
- docs/ExtensionUI.md
- docs/Installation.md
- docs/LowCode.md
- docs/Projects.md
- docs/ReportingIssues.md
- docs/RunDebug.md
- docs/ServerSide.md
- docs/SettingsReference.md
- docs/Studio.md
- docs/_config.yml
- docs/index.md
- docs/introduction.md
Uses a kramdown extension to markdown to show a warning box.
> make new docs location more prominent

- package-lock.json
- src/api/index.ts
> Always delete cached authentication promise when request fails (fix #1196)

- src/providers/ObjectScriptCodeLensProvider.ts
Added `Copy Invocation` to Queries too
In this case will copy `##class(dc.CityTable).ListFunc()`
> Copy query

- src/providers/FileSystemProvider/TextSearchProvider.ts
> Properly report search matches for super classes

- .github/CODEOWNERS
This PR deletes the .github/CODEOWNERS file. Subsequent PRs will no longer automatically request a review from @daimor
I intend to wait for approval from all three of my PMC colleagues before merging this.
> No longer autorequest PR review from @daimor

- src/extension.ts
- src/providers/FileSystemProvider/FileSystemProvider.ts
> Improve the MAC and INT server-side new file stubs

- src/utils/FileProviderUtil.ts
> Fix display of routines inside a server-side project

- src/commands/serverActions.ts
This PR adds an option to the Server Actions menu for selecting a Studio Add-In to open. It queries the server for the list of all Add-Ins, so it should support any customer-created Add-Ins (if that's even a thing). I removed the hard-coded SOAP Wizard option added by #1107 since that functionality is covered by the new option.
> Add option in Server Actions menu to open Studio Add-Ins

- snippets/objectscript-class.json
> Fix class name regex in Production snippets

- src/explorer/models/rootNode.ts
This PR changes the implementation of the Explorer to use the GET /%25SYS/cspapps API to populate the list of web applications instead of StudioOpenDialog so REST web applications are no longer shown. It also changes the behavior for "other" files to reduce the amount of unneeded data returned by the server.
> Don't show REST APIs in Explorer CSP Files list

- src/commands/webSocketTerminal.ts
> Fix WebSocket Terminal `del` key

- src/commands/unitTest.ts
> Don't create unit test items in workspace folders that don't support running tests

- CHANGELOG.md
- README.md
I will do the release on Monday
> Prepare 2.12.1 release

- src/languageConfiguration.ts
* Restore auto-closing of braces and parentheses that #1311 broke
* Add auto-closing of quotes
> Restore auto-closing braces and parentheses

- src/commands/documaticPreviewPanel.ts
- src/commands/restDebugPanel.ts
- src/commands/studio.ts
- src/commands/webSocketTerminal.ts
- src/extension.ts
- webview/preview-dark.svg
- webview/preview-light.svg
This is a small non-functional change that I think adds some UX polish.
> Use ISC icon for webviews

- src/commands/compile.ts
> Only remove blank line ending for web application files

- src/commands/unitTest.ts
I assumed that renaming files triggered both a "create" event on the new URI and a "delete" event on the old URI, but that wasn't true. This PR adds a listener for the "rename" event as well so the Test Explorer tree is always accurate.
> Update Test Explorer when test classes are renamed

- src/commands/unitTest.ts
Workaround for https://github.com/microsoft/vscode/issues/207574. Suggested by @ollitanska.
> Fix manual refresh of Test Explorer

- src/commands/project.ts
- src/explorer/explorer.ts
> Update timestamp when modifying a project

- package.json
- src/commands/unitTest.ts
This PR adopts a [new VS Code API](https://code.visualstudio.com/updates/v1_91#_finalized-debugsessionoptionstestrun-api) that should improve the UX around debugging unit tests.
> Associate unit test debug sessions with the test runs

- src/commands/project.ts
> Add confirmation dialog when deleting a project

- src/api/index.ts
- src/extension.ts
This might be useful in the future for gating features.
> Store server version in workspace state

- src/commands/addServerNamespaceToWorkspace.ts
> More UI tweaks

- src/commands/webSocketTerminal.ts
> Adopt `HasRichCommandDetection` sequence

- src/debug/debugSession.ts
> Show error message when debugging fails to start

- src/commands/restDebugPanel.ts
> Fix generating of URL when debugging REST services

- src/commands/studio.ts
> Handle errors when fetching server-side source control menu options fails
