intersystems-community/vscode-objectscript

src/providers/ObjectScriptDiagnosticProvider.ts

Whenever we have <script> tags within objectscript embedded html (&html< ... >) lot's of js keywords were tried to be recognized as objectscript keywords. This led to highlighting most of javascript code with "Unrecognized command" warning.
This PR is only a quick workaround. Need more detailed implementation, since there are some cases when this implementation might not work perfectly.

first path implementation for recognizing js <script> tags

---

package.json

Simply remove the anomalous suffix text.

fix #140 Remove ' Configuration' suffix from settings section title

---

package.json
src/api/index.ts
src/commands/compile.ts
src/commands/studio.ts
src/extension.ts

Addresses the following studio extension VSCode gaps:
- MenuItem save flags are not supported
- No differentiation between different menus - Added the menu name to the right of the menu item
- Studio actions produce JSON output - Added an option to enable the output, but it is disabled by default
- For prompts, AfterUserAction supplies the user's text in Answer instead of Msg (with Answer indicating yes/no/cancel); also, there's no yes/no/cancel, it's just text or cancel
- Actions can't open CSP pages (which should include authentication, similar to Atelier)
- Actions can't open documents
- Actions can't modify document text
- ObjectScript explorer needs to support context menus - A context menu was added to the explorer that displays the available context actions
- No support for …

Add more studio actions

---

.github/workflows/main.yml
src/commands/compile.ts
src/utils/index.ts

Respect original EndOfLine in file, while load changes from server

---

.github/workflows/main.yml
src/api/index.ts
src/extension.ts
src/utils/index.ts

resolves #105, resolves #154, resolves #153

fix several issues with terminal in docker

---

src/api/index.ts
src/commands/compile.ts

Add alerts in the bottom right when importing fails. The read-only error will now appear in the bottom right instead of a modal.

Alert on import error

---

src/commands/delete.ts
src/commands/studio.ts
src/providers/DocumentContentProvider.ts

When files are deleted, the Studio Extension's AfterUserAction method is called. 
Also, a bug was fixed where some classes were being flagged as CSP files and could not be opened.

Add AfterUserAction support when deleting files

---

package.json

This PR fixes #176. The `vscode-objectscript.studio.actions` command was recently renamed in one PR and amended in another PR. The resulting merge was incorrect.

fix #176 Remove obsolete menu reference to renamed command

---

src/providers/ObjectScriptDiagnosticProvider.ts

#97 resolved diagnostic issue in html style block

---

src/explorer/explorer.ts

fixed extra namespaces per instance in explorer view

---

src/providers/FileSystemPovider/FileSystemProvider.ts

If necessary, the Studio Extension's AfterUserAction method is called after creating or deleting a file on isfs.

Support AfterUserAction when creating and deleting files on isfs

---

package.json
src/extension.ts
test-fixtures/test.code-workspace

Make ServerManager extension as optional, do not prevent this extension working.

---

package.json
src/explorer/models/nodeBase.ts
src/explorer/models/rootNode.ts
src/explorer/models/workspaceNode.ts
src/extension.ts

Show system items in ObjectScript Explorer view

---

package.json
src/api/index.ts
src/commands/compile.ts
src/commands/serverActions.ts
src/debug/debugSession.ts
src/extension.ts
src/providers/DocumentContentProvider.ts

This PR closes #193.
@bourette you may like to try the VSIX that will be built from this PR.

fix #193 Add 'isfs-readonly' scheme

---

CHANGELOG.md
README.md

This fixes #124, adding detail to CHANGELOG. It also updates README to reflect introduction of `intersystems.servers` object for connection definitions.

Fix #124 Add details to CHANGELOG and README

---

package.json
src/api/index.ts
src/commands/serverActions.ts
src/extension.ts
src/providers/FileSystemPovider/FileSystemProvider.ts
src/utils/index.ts

This PR fixes #192 and also takes advantage of intersystems.servermanager's ability (0.0.4+) to store connection passwords in the local keychain.
It has required a lot of refactoring, partly because keychain access has to be async.
Additional work was done in the FileSystemProvider to suppress unnecessary server access attempts, e.g. to /node_modules, /.vscode and /.git

Reinstate password prompting, and leverage servermanager for password storage in keychain

---

src/providers/ObjectScriptCompletionItemProvider.ts

fix intellisense, broken with the release (#225)

---

README.md
src/extension.ts

This PR fixes an issue identified in #224. If the `server` property of `objectscript.conn` was pointing to an entry in `intersystems.servers` for which the password had been stored in the keychain, we were not retrieving it unless the workspace also referenced the same server via an isfs or isfs-readonly uri.

Fetch keychain-stored password when objectscript.conn.server is specified

---

package.json
src/explorer/explorer.ts
src/explorer/models/cspFileNode.ts
src/explorer/models/rootNode.ts
src/explorer/models/workspaceNode.ts
src/extension.ts
src/providers/DocumentContentProvider.ts

This fixes #233 and some other things in ObjectScript Explorer.
- Use an icon for "View Another Namespace" instead of a text label.
- Add prompt text to quickpick.
- Fix broken "Remove" action on added root folders.
- Add icons to root folders.
- Differentiate between automatically created ones and manually added (and thus removable) ones.
- Suppress Export command on CSP Files folder and its contents because it doesn't currently work. If/when implemented/fixed it will be easy enough to reinstate the Export command.
- Fix broken opening of CSP files.
- Expose "Show/Hide System" and "Show/Hide Generated" as icons for better discoverability.
Example:

fix #233 and make other improvements/fixes to ObjectScript Explorer

---

src/commands/compile.ts
src/commands/delete.ts
src/commands/export.ts
src/commands/studio.ts
src/explorer/models/classNode.ts
src/explorer/models/cspFileNode.ts
src/explorer/models/packageNode.ts
src/explorer/models/rootNode.ts
src/explorer/models/routineNode.ts
src/explorer/models/workspaceNode.ts
src/providers/DocumentContentProvider.ts

This fixes #237.
It also adds visual differentiation between files in OE that will open from the server and those that will open from the local workspace.
Problem indicators will display for the latter.

fix #237 Don't open wrong local document from ObjectScript Explorer

---

src/commands/compile.ts

This PR fixes #284. It aligns our compare with the built-in one that VS Code will present if a similar conflict occurs when saving an isfs:// file.

fix #284 swap sides in Compare following import conflict

---

docs/Configuration.md
docs/Installation.md
docs/RunDebug.md
docs/ServerSide.md
docs/Settings.md
docs/index.md
docs/workspace.md

This PR fixes #293 
Inter-document links have been standardized to use `./XXX` format and to match exactly the case of the target document names. Inconsistent capitalization of document names has not been addressed, i.e. a few remain all lowercase.

fix #293 Fix broken image and inter-document links

---

src/api/index.ts
src/extension.ts

This PR fixes #285 
It makes the extension export a function `serverForUri` that takes a `vscode.Uri` and returns an object containing sufficient information for the caller to connect to the InterSystems server where the document gets imported and compiled.
It also adds a `serverDocumentUriForUri` API function with which the caller can get a uri for the server-side document of the uri passed to it. This is useful when the caller has a file:// uri and needs the corresponding  objectscript:// uri.
The initial use-case for these APIs was a language server.

fix #285 export serverForUri function as API

---

src/extension.ts
src/utils/index.ts
src/utils/inputBoxManager.ts

Fixes #302 by only showing one input box at a time, deduplicating per server

fix #302: manage use of vscode.window.showInputBox

---

src/extension.ts

This PR fixes #332 by writing a message to the ObjectScript output channel when the extension hooks up to proposed APIs during activate.

fix #332 Announce when proposed APIs are being used

---

src/api/atelier.d.ts
src/providers/FileSystemPovider/FileSearchProvider.ts

This PR fixes #334 
When running with proposed API enabled and isfs or isfs-readonly folders the QuickOpen field (Ctrl/Cmd+P without Shift) will now search server-side document names.

fix #334 connect FileSearchProvider call to server

---

package.json
src/commands/connectFolderToServerNamespace.ts
src/explorer/explorer.ts
src/extension.ts

This PR implements #330 
With one or more local folders open but lacking `objectscript.conn` settings, the ObjectScript view displays a button that runs the new `connectFolderToServerNamespace` command, and a link to `hideExplorerForWorkspace` (also new).
Together with a new `showExplorerForWorkspace` these commands are also available on the palette.

Add command to link local folder to server (#330)

---

src/api/index.ts
src/debug/debugSession.ts
src/debug/xdebugConnection.ts

fix for debugger target with spaces, 
fix when it stops working after a few debugging, now it should reuse cookies and successfully start, or even just warn that it did not start 
This PR fixes #257
This PR fixes #341 
This PR fixes #342

Fix issues with debugger

---

src/commands/viewOthers.ts
src/utils/index.ts

This PR fixes #348 
viewOthers was always using AtelierAPI based on workspace settings; now goes based on current file (e.g., fixes View Other with multiple isfs folders pointing to different servers, or without a workspace default server properly configured)
In currentFile, for CSP files, should use forward slashes (were backslashes on Windows, which prevented "view other" for working on CSP files in isfs).

Fix #348 : correct context for AtelierAPI; fix CSP slashes

---

package.json
src/commands/jumpToTagAndOffset.ts
src/extension.ts

This PR fixes #267 
A new command, "Jump to Tag + Offset" (also launched by clicking via the position status bar element, as @gjsjohnmurray suggested) supports jumping to tag[+offset] within .MAC and .INT routines.

Jump to tag and offset

---

package.json
src/providers/FileSystemPovider/FileSystemProvider.ts

Also enables them for source control actions even if they're XML files (e.g., DFI and some other custom document types used in Interoperability and HS)
This PR fixes #361

Fix #361, support opening "other" doc types via isfs

---

src/commands/studio.ts

This PR does not fix #259 but does address https://github.com/intersystems-community/vscode-objectscript/issues/259#issuecomment-682088028 and some related issues my team has observed.
Use case:
We have a Source Control > Undo Check Out menu item for our Perforce-based extension. This will return reload=true. The problem was twofold - we weren't checking/acting on the "reload" flag from AfterUserAction, and when we did, we were detecting the revert as an edit and blocking it unless the user checked the file out again (obviously not correct).
There isn't really a clean way to detect this case, so we now track URIs for which we've requested a reload and ignore the next "attempted edit" on them. While not the neatest, the solution is at least localized to the legacy studio command set of …

Fix extension reload

---

package.json
src/extension.ts

initial support for working together with language-server

---

src/api/index.ts
src/commands/compile.ts
src/providers/FileSystemPovider/FileSystemProvider.ts
src/utils/index.ts

This PR resolves #383
To provide the server-side storage, define a web application named `/_vscode` like this:
(alter the Physical Path value to suit your platform and install folder)
An isfs-type workspace root folder that connects to a namespace on this server can now write and read folder-specific settings, e.g.
Folder-specific snippets file can be created via `Preferences: Configure User Snippets`
To edit the server-side namespace-specific files (all namespaces) directly through VS Code, add an isfs-type root folder with the following uri:
```
isfs://servername/_vscode?ns=%SYS&csp
```
For a single namespace (e.g USER):
```
isfs://servername/_vscode/USER?ns=%SYS&csp
```

Support server-side (isfs) folder settings, snippets, debug configs etc

---

CHANGELOG.md

A CI problem with the release procedure (v1.0.0 being initially saved as a draft) prevented 1.0.0 from getting published. Releasing 1.0.1 to resolve this.

CHANGELOG update for 1.0.1

---

src/debug/debugSession.ts
src/debug/xdebugConnection.ts

Correct encoding for values, variable names, methods names returned from Debugger API
This PR fixes #414

Fixed showing variable values in debugger

---

package.json
src/commands/serverActions.ts

This PR fixes #443 
New variables are:
- `${serverUrl}` - for example `http://localhost:52773`
- `${serverAuth}` - for example `&IRISUsername=_SYSTEM&IRISPassword=SYS`
- `${ns}` - the raw `ns` parameter of the connection. Different from the already-defined `${namespace}` variable.
An example of how the new capabilities can launch [WebTerminal](https://openexchange.intersystems.com/package/WebTerminal):
```json
"objectscript.conn": {
"server": "vscodelab",
"ns": "%SYS",
"active": true,
"links": {
"$(terminal) WebTerminal": "${serverUrl}/terminal/?ns=${ns}${serverAuth}"
}
}
```

fix #443 support more ${...} variables in server menu links

---

package.json
src/commands/compile.ts

This PR fixes #464 
It adds the `objectscript.overwriteServerChanges` setting (default = `false`). This setting intentionally only affects import from file-type uris. When server-side editing (isfs) is being used, conflicts are always notified.

fix #464 add objectscript.overwriteServerChanges setting

---

src/providers/FileSystemPovider/FileSearchProvider.ts

This PR fixes #467
The same search as showen on the original issue now returns thus:

fix #467 improve Quick Open (ctrl+p) on isfs (uses proposed API)

---

src/extension.ts

fix #471 give OE-opened files a "(read-only)" suffix (requires proposed API)

---

src/utils/index.ts
syntaxes/objectscript-class.tmLanguage.json
syntaxes/objectscript-macros.tmLanguage.json
syntaxes/objectscript.tmLanguage.json

This PR fixes #337 and also corrects TextMate handling of identifiers that contain Unicode characters.

fix #337 handle Unicode chars in identifiers

---

CHANGELOG.md
README.md

@daimor we need to publish 1.0.5 before LS 1.0.5 so at to avoid FoldingRangeProvider conflict.
cc @isc-bsaviano

CHANGELOG and README for 1.0.5

---

src/commands/serverActions.ts

This PR fixes #490 
The server action menu, accessed by clicking on the connection's panel in the status bar, now targets its Open Class Documentation onto the currently open class if any.
Side-effects of this change:
- the ${classname} substitution no longer includes a redundant ".cls" suffix. This is a breaking change but seems low-risk because this feature doesn't appear to have been documented yet.
- a new ${classnameEncoded} substitution has been added, suitable for use in a URL querystring.

fix #490 make Documatic launcher class-specific

---

src/api/index.ts
src/providers/DocumentContentProvider.ts
src/providers/FileSystemPovider/TextSearchProvider.ts

This PR fixes #495, including suppressing display of search results in output channel.

fix #495 display TextSearchProvider results from non-primary root

---

src/api/index.ts
src/extension.ts

This PR fixes #503
Previous work to standardize contents of thrown errors broke interactive password prompting in 1.0.5

fix #503 ask for password when needed

---

src/providers/FileSystemPovider/FileSystemProvider.ts

This PR fixes #501 by ensuring .prj items never appear in the tree.

fix #501 exclude Studio projects from isfs

---

src/api/index.ts
src/commands/serverActions.ts
src/extension.ts

This PR fixes #510
It also adds pathPrefix info to the "Connected as" tooltip of the status bar panel when pathPrefix is set.

fix #510 respect pathPrefix on server action URLs

---

src/utils/index.ts

This PR fixes #516 
Windows shell (cmd.exe) does not handle single quotes so the call to `exec` to lookup docker port fails. Works as expected after removing the quotes.

fix docker port lookup command for Windows

---

package.json
snippets/objectscript-class.json

"View other" should work not just for COS classes/routines. Custom Studio documents could be XML or in some other format and have output from "View other". Hence, when in a folder in a workspace that has the ObjectScript extension enabled, whatever document is in context should allow you to use "View other" because it is not possible to predict all possible formats of custom Studio documents.

Enable "View other" for custom Studio documents

---

src/utils/index.ts

Custom Studio documents will never have / in their name (which is only applicable to CSP files). Hence, if the "name" variable in currentFile() has a leading /, it should be stripped so that the document name is passed correctly to the Atelier API when updating on the document on the server.

Fix leading / issue that prevents custom Studio documents from being saved on the server

---

snippets/objectscript-class.json
snippets/objectscript.json

This PR fixes #546
It also:
- adopts changes by @isc-solon to add a ///-comment tabstop at the start of all snippets used in class definitions, obsoleting PR #537
- standardizes body layout in definitions to reflect layout of result.
- uniformly uses Capitalized command names and UPPERCASE function names in ObjectScript.
- tidies up how duplicate tabstops are used.
- adds descriptive default text to more tabstops.

 Tidy up and improve snippet definitions, inc fix for #546 

---

package.json
src/providers/WorkspaceSymbolProvider.ts

Current implementation of symbol search (Cmd/Ctrl + T) is to only search for classes, routines and methods. Expand this default to also search include files.
Added a setting to toggle whether ALL studio document types should be searched for rather than just the defaults.
Default is still to only search classes, routines, methods and include files (added).
Can toggle on searching for all Studio documents. Default is to NOT search (as it can be expensive if many CSP files present).
Removed byClasses because it can be handled by StudioOpenDIalog.

Support searching for all Studio document types when using Cmd + T.

---

src/api/index.ts
src/debug/debugSession.ts
src/providers/DocumentContentProvider.ts
src/providers/FileSystemPovider/FileSystemProvider.ts
src/utils/index.ts

This PR implements #450 
isfs workspace root uris can now specify the namespace as a colon-separated suffix on the server name instead of adding the ?ns=XYZ queryparam.
Example of a .code-workspace file that demonstrates the new syntax alongside the old:
```
{
"folders": [
{
"name": "iris201:USER",
"uri": "isfs://iris201/?ns=USER"
},
{
"name": "iris201:USER new style",
"uri": "isfs://iris201:USER/"
},
{
"name": "iris201:USER new style - webfiles",
"uri": "isfs://iris201:USER/?csp"
},
{
"name": "iris201:%SYS",
"uri": "isfs://iris201/?ns=%SYS"
},
{
"name": "iris201:%SYS new style",
"uri": "isfs://iris201:%SYS/"
}
]
}
```

implement isfs://server:namespace/ alternative syntax (#450)

---

src/providers/FileSystemPovider/FileSystemProvider.ts
src/utils/index.ts

This PR fixes #552
See PR #384 for how to enable server-side storage for settings, snippets etc within isfs workspace roots. All *.code-snippets files in the corresponding server-side directory will now get loaded.
A convenient way to create such a file is to run the `Preferences: Configure User Snippets` command when the workspace is open, then pick `New Snippets file for 'XYZ'` where `XYZ` is the isfs folder name you want to store the file under.
In a multiroot workspace snippets from every isfs-type root are available to the whole workspace. This is standard VS Code behaviour.

fix #552 load server-side code snippets from isfs workspace roots

---

docs/ServerSide.md

The new syntax was implemented in PR #551 in response to issue #450. It shipped in 1.0.8

Update documentation to reflect the new isfs namespace syntax

---

src/extension.ts

not public flag `ignoreInstallLanguageServer`
for automated environments, where language-server may not work

ignoreInstallLanguageServer flag

---

src/api/index.ts
src/extension.ts

This PR fixes #586
If the `server` property of `objectscript.conn` names a server that doesn't exist in `intersystems.servers` the ObjectScript Explorer was empty and its Refresh button produced an error.

fix #586 handle reference to nonexistent server spec

---

src/providers/FileSystemPovider/FileSearchProvider.ts

This PR fixes #581
Prior to this change, if a workspace's isfs folder specified a path then the QuickOpen (Ctrl+p) results were not limited to that path.
For example, QuickOpen on a workspace referencing `isfs://local:samples/Cinema` would incorrectly include matches outside the Cinema package.
We now also respect `?type=cls` or `?type=rtn` parameters, and avoid collapsing foo.bar.1.int completely (foo/bar/1.int) but instead behave as Explorer does (foo/bar.1.int)
We do not apply any `filter=XYZ` parameter because the docnames endpoint of the Atelier API doesn't support doing this server-side.

fix #581 constrain QuickOpen results to isfs path if set

---

.gitignore
src/debug/debugSession.ts

Currently, when the debugger sends a breakpoint command to the server for a class file that has multiple packages, the file URI gets generated incorrectly. The `convertClientPathToDebugger()` method doesn't convert all "/" in the isfs URI to ".", which causes the URI to be formatted in a way that the server doesn't understand. For example, here's the log of a `breakpoint_set` command that fails:
```
^IRIS.Temp.Atelier("debug",89842,1,23)="Received:breakpoint_set -i 7 -t line -s enabled -f dbgp://|USER|User.test%2Ftest.cls -m tst -n 2"
^IRIS.Temp.Atelier("debug",89842,1,24)="Calling state breakpoint_set"
^IRIS.Temp.Atelier("debug",89842,1,25)="mapping: USER:User.test/test.cls:tst:2 -> :-1"
^IRIS.Temp.Atelier("debug",89842,1,26)="Event:error|<response command='breakpoint_set' …
```

Fix debugging breakpoint command message when class has multiple packages

---

package.json
src/extension.ts

This PR fixes #599
Previous fix for #455 used a proposed API (`workspace.registerResourceLabelFormatter`) and so was only available to users prepared to run from a beta VSIX with the necessary runtime argument.
This PR reimplements the same feature using the `contributes/resourceLabelFormatters` contribution point.

fix #599 use `contributes/resourceLabelFormatters` instead of proposed API

---

src/debug/debugSession.ts

We're considering adding support for drilling down into OREF's during debugging in the Atelier debugger so we'll need this code back into effect to get the most of the server enhancements.

Capture children of eval command property response if they exist

---

src/api/index.ts
src/extension.ts

This PR fixes #616
Also fixes a case where password "undefined" was sent to the server, potentially causing noise in the security audit log.

fix #616 Avoid prompting for password that is already saved

---

package.json
src/commands/compile.ts
src/extension.ts

This PR fixes #594 
Adds the "objectscript.compileOnSave" boolean configuration option with default value `true`. When `false`, saving an InterSystems file will not automatically compile it.

Add configuration option to turn off post-save compile

---

package.json
src/extension.ts

This PR fixes #634
When using the ObjectScript Explorer, REST requests are made to the doc endpoint trying to sync the output channel content with the server.
Renaming the output channel language as suggested in #634 stops the extra requests.

Rename the Output Channel Language

---

src/commands/viewOthers.ts

This PR fixes #363
If you click "View Other" on a document whose server has Atelier API version 4 or greater and are in a method or routine, the cursor position in the "other" document when opened will correspond to the cursor position in the original document.

Jump to corresponding location in "other" document if server api version is 4 or greater

---

package.json
src/api/index.ts

This PR fixes #457 
Adds the `objectscript.multilineMethodArgs` boolean configuration option with default value `false`. If set to `true` and the server's Atelier API version is 4 or greater, the `format=udl-multiline` query parameter will be passed to all calls to the [Atelier API GetDoc endpoint](https://docs.intersystems.com/irislatest/csp/docbook/Doc.View.cls?KEY=GSCF_ref#GSCF_ref_getdoc).
@daimor I'm marking this as a draft until I make some corresponding changes to the Language Server but I think this is ready to merge otherwise.

Add configuration setting for multiline method arguments

---

package.json
src/commands/compile.ts
src/extension.ts

This PR fixes #595 
Adds 2 new commands, `vscode-objectscript.compileOnly` and `vscode-objectscript.compileOnlyWithFlags`, which allow the user to compile the currently open InterSystems file without saving its contents. The compilation will be aborted an a warning message will be presented if the user tries to compile a dirty file.

Add commands for compiling current file

---

package.json
src/commands/viewOthers.ts
src/extension.ts

This PR fixes #309 
Modifies `viewOthers()` to take boolean argument `forceEditable`. When `forceEditable` is `true`, the other document will open using the writeable `isfs` schema regardless of the user's `objectscript.serverSideEditing` setting. If `forceEditable` is `false` (the case for the `vscode-objectscript.viewOthers` command), we will defer to the user's `objectscript.serverSideEditing` setting like before. New menu option `Edit Other` will appear below `View Other` if an InterSystems file with schema `file` is open.

Add "Edit Other" command and menu option

---

package.json
src/commands/compile.ts
src/commands/export.ts
src/explorer/models/rootNode.ts
src/extension.ts
src/utils/index.ts

This PR fixes #147 and fixes #449 
@daimor @gjsjohnmurray I will send the dev vsix for this PR to the InterSystems devs that requested it and will promote this from draft when I get their feedback.
Changes made:
- Enable exporting of CSP application files from ObjectScript Explorer
- Import non-InterSystems CSP application files upon save.
- Import individual web application text files from the file explorer using "Import ..." commands.
- Import all text files in exported web application folder using "Import ..." commands.
- Color .csr files
How to use:
- Open a workspace that contains web app files in a csp directory that matches the path on the server.
- Open a text file in your local copy of the web app files, edit it, and then save it. The file will be automatically synced to the …

Improve client-side CSP workflow

---

src/extension.ts

fix #651 don't switch to File Explorer view when opening one from ObjectScript Explorer

---

src/providers/DocumentLinkProvider.ts

This PR fixes #657 
Use reveal range when opening links rather than just moving the cursor which does not scroll to the correct position.

Use reveal range instead of moving the cursor

---

src/api/index.ts
src/commands/compile.ts
src/commands/export.ts
src/commands/viewOthers.ts
src/providers/DocumentContentProvider.ts
src/providers/FileSystemProvider/File.ts
src/providers/FileSystemProvider/FileSystemProvider.ts
src/utils/index.ts

This PR fixes #683
- Updates workspace-cached mtime when file is opened again
- Revises stat() method handling to detect when server-side etag has changed, triggering refresh of client cache entry.
- Enhances the 'failed compilation' error messages with a button to show the output channel.
@isc-bsaviano this PR should mean the work you proposed doing to detect server-side changes is no longer needed. Please try the VSIX this PR builds, or point relevant internal users at it for verification.

fix #683 better isfs handling of server-side changes

---

src/providers/ObjectScriptCompletionItemProvider.ts

https://github.com/microsoft/vscode/commit/24f9000e97e6a798cf565bb7fbde810ae21ae667 added CompletionItemLabel as an alternative type for the label property of CompletionItem. This broke our build, which always pulls vscode.d.ts and vscode.proposed.d.ts from vscode/main
Example of broken build is at https://github.com/intersystems-community/vscode-objectscript/pull/661/checks?check_run_id=2884905256

Fix build broken by recent vscode.d.ts change

---

src/debug/debugSession.ts
src/debug/xdebugConnection.ts

Add watchpoint support

---

.vscodeignore
package-lock.json
package.json
src/providers/FileSystemProvider/FileSystemProvider.ts

This PR fixes #695
During testing I also fixed .vscodeignore so `vsce package` still works despite the vsce@1.92.0 breaking change (see https://github.com/microsoft/vscode-vsce/issues/576)

fix #695 Mark isfs root bad if unreachable, and package correctly with latest vsce

---

package.json
src/commands/studio.ts

This PR fixes #691
With `"objectscript.serverSourceControl.disableOtherActionTriggers": true` the 'Other Studio action' server-side source control calls are suppressed.
The calls currently made (and thus suppressed by this setting) are:
- AttemptedEdit = 0
- CreatedNewDocument = 1
- DeletedDocument = 2
- FirstTimeDocumentSave = 7

fix #691 Add `objectscript.serverSourceControl.disableOtherActionTriggers` setting

---

src/providers/FileSystemProvider/TextSearchProvider.ts

This PR fixes #713 
Edited `provideTextSearchResults()` to send `options.maxResults` to the server if it's non-`null`. If the value is `null` (meaning "send an unlimited number of results"), a value of 100,000 is sent to the server because it's not possible to specify "unlimited".

Allow configuration of server side search max results

---

src/commands/compile.ts

This PR improves the wording from #716, which addressed #677

Improve wording of confirmation message for namespace compile command

---

src/commands/studio.ts

This PR fixes #701, #703
Errors reported by AfterUserAction were previously ignored, now they are displayed in the output window.
When checking out a file your edit was always undone. Now it only undoes the edit if the user selects "No" or "Cancel" or if an error is reported when trying to check out the file.

Display AfterUserAction errors and remove undo on successful checkout

---

src/api/index.ts

This PR fixes #721
Catch and handle HTTP 503 responses, which are sent from the server when it's out of licenses.

Gracefully handle 503 responses from server

---

src/providers/DocumentContentProvider.ts

Don't return ISFS URI with CSP query parameter if file is a class or routine

---

src/commands/studio.ts
src/providers/DocumentContentProvider.ts

This PR fixes #731
CSP documents can now be opened through a studio extension and reveal range is used to scroll to the correct position in each document.

Studio action open document fixes

---

src/debug/debugSession.ts
src/debug/xdebugConnection.ts

This PR adds support for [conditional breakpoints.](https://code.visualstudio.com/docs/editor/debugging#_conditional-breakpoints) Note that due to a limitation in the Atelier debugger implementation, we can only support hit conditions that are integers instead of more complex expressions.

Add support for conditional breakpoints

---

CHANGELOG.md

Debugger: Conditional breakpoint with condition but no hitCondition cannot be set (#766)
This PR updates changelog to create a new release for fix of #766 and #768

Prepare for 1.1.1 release

---

src/providers/FileSystemProvider/FileSystemProvider.ts

This PR fixes `FileSystemProvider` mtime caching. Previously, the cache would get constantly overwritten so calls to `GET /doc` wouldn't include the `IF_NONE_MATCH` header, forcing the server to send the full contents of the file back every time. This fix corrects this problem so the proper mtime is sent with `GET /doc` requests.

Fix `FileSystemProvider` mtime caching

---

docs/SettingsReference.md
package.json
src/providers/WorkspaceSymbolProvider.ts

- Search for all class members, not just methods.
- Don't search for Studio documents so we avoid duplication functionality that's covered by the `FileSearchProvider` (Quick Open).
- Properly translate `query` to a `%MATCHES` compatible pattern while following the interpretation guidelines.
- Use the same `SymbolKind` as the Language Server for all class member types for consistency.
- Use the `vscode.executeDocumentSymbolProvider` command to find the location of the symbol.
- Improve performance by only computing symbol location when selected by the user.
- Remove unneeded setting `"objectscript.searchAllDocTypes"`.

Overhaul `WorkspaceSymbolProvider`

---

src/utils/index.ts

Append `.pkg` to package name when passed to source control / server command extensions

---

src/commands/serverActions.ts
src/utils/index.ts

With the up coming version of IRIS with embedded python, it can be useful to have an easy option to gain shell access in the container

Add option to open shell in docker

---

src/providers/DocumentContentProvider.ts

Check all local folders in multi-root workspace for local copy of file

---

package.json

fix default values for export

---

package.json

This PR improves #800 and fixes #799
@daimor @gjsjohnmurray I think we should do a 1.2.2 release once this is merged because #799 is causing users to downgrade

Restore defaults for all export settings

---

package.json
src/test/runTest.ts

Hide 'vscode-objectscript-output' language from selector (fixes #805)

---

src/commands/studio.ts

If a user opens a second namespace using the `+` button in the ObjectScript Explorer and tries to run a Studio Action, the menu options shown will be from the original namespace. This PR makes the menus namespace aware.

Show menu options from correct namespace for Studio Actions in ObjectScript Explorer

---

src/commands/studio.ts

Properly return menu options for the `Server Command Menu` for `isfs-readonly` files

---

src/extension.ts

This PR fixes an issue where beta and dev vsix's cannot be activated with proposed APIs disabled.
See #781, starting from https://github.com/intersystems-community/vscode-objectscript/issues/781#issuecomment-997830201 for how this issue manifests.

Fix proposed API registration

---

src/commands/studio.ts

This PR fixes #171
Changes made:
- Add a function to `StudioActions` class that checks if a source control class is enabled.
- Inform the user when they attempt to access the source control or server command menus when a source control class isn’t enabled.
- Don’t attempt to automatically fire a studio action if a source control class isn’t enabled.

Improve behavior when no Source Control class is enabled

---

src/commands/studio.ts

This PR fixes #781 
Fixes a typo that caused Studio Actions that required no user input to be treated as `Attempted Edit` Studio Actions.

Fix `Attempted Edit` Studio Action condition

---

src/providers/WorkspaceSymbolProvider.ts

This PR fixes #375
Changes made:
- Loop through folders in the workspace and determine which server and namespace they’re connected to.
- Filter out duplicate server/namespace combos to avoid querying a server multiple times for the same namespace.
- Filter out results from system classes in non-%SYS namespaces when a workspace is connected to both the %SYS and a non-%SYS namespace for the same server to avoid duplicate results.

Provide `WorkspaceSymbols` for all servers in workspace

---

docs/SettingsReference.md
package.json
src/commands/export.ts
src/explorer/models/rootNode.ts
src/extension.ts

This PR fixes #129
Changes made:
- Modify `"vscode-objectscript.export"` to do the following:
- Don’t allow the user to select a virtual folder as the export destination.
- If there are no suitable folders in the workspace, notify the user and exit.
- Replace the call to `AtelierAPI.getDocNames()` with a call to the StudioOpenDialog query to improve performance and to allow the filtering out of system items when the namespace is not `%SYS`.
- Ask the user for confirmation and allow them to exclude individual files from the export list before starting the export.
- Add `"vscode-objectscript.exportCurrentFile”` command that exports the currently opened file, if it was opened from the ObjectScript Explorer.
- Change `RootNode.getList()` query to only SELECT needed columns from …

Improve exporting

---

src/commands/export.ts
src/utils/index.ts

This PR fixes #35 and fixes #313
Previously, DFI files could only be edited and synced to the server using server-side editing by adding `?filter=*.dfi` to an `isfs` folder URI. This PR adds support for client-side editing of DFI files.
Changes made:
- Export DFI files to folder `dfi` instead of `oth` when `objectscript.export.addCategory`  is `true`.
- Export DFI files to subfolders when `objectscript.export.atelier` is `true`.
- Sync DFI files to the server on save if the file's path matches the export settings (i.e. if `objectscript.export.addCategory` is `true`, the files must be in the `dfi` folder).

Improve client-side DFI workflow

---

src/providers/FileSystemProvider/FileSystemProvider.ts

Exempt isfs web app files with .csp extension from usual pre-save sanity checks

---

CHANGELOG.md
README.md
docs/SettingsReference.md
package-lock.json
package.json
src/commands/export.ts
src/commands/studio.ts
src/debug/debugSession.ts
src/explorer/models/rootNode.ts
src/extension.ts
src/providers/WorkspaceSymbolProvider.ts
src/test/runTest.ts
src/utils/index.ts

Earlier I created a new branch called **prerelease** from the source that I erroneously published manually to Marketplace today as 1.3.2022011401 after a `vsce package` command that omitted the `--pre-release` switch.
This PR updates that branch with the fixes and enhancements we released today as 1.4.1
The prerelease branch is intended to be long-living. In future it'd be good to add CI so we can publish pre-releases more automatically from this, which should ensure the `--pre-release` switch doesn't get forgotten again.

Merge 1.4.1 release changes into prerelease branch

---

src/utils/index.ts

This PR fixes #734 by using `docker-compose.exe` instead of  `docker-compose` on windows.

use docker-compose.exe on windows

---

package-lock.json
package.json
src/api/index.ts

This PR fixes #841
A recent security upgrade of node-fetch broke our webpacked VSIX. Solution is to use the node-fetch-cjs wrapper, a helper for CommonJS projects.
In the future, when VS Code get a newer Node.JS version by moving to a newer Electron we may be able to switch back to using node-fetch if required.

Switch to `node-fetch-cjs` (fixes #841)

---

.github/workflows/main.yml
src/extension.ts

This PR fixes #837
@isc-bsaviano please use the dev VSIX to verify that this meets the need without exposing passwords that may have come from Server Manager's authentication provider.

Allow serverForUri to return password for unnamed server (#837)

---

.github/workflows/main.yml
.github/workflows/prerelease.yml

Publish either a pre-release or an ordinary one, depending on whether the release was tagged in the prerelease branch or the master branch.

CI release action must only publish one type of vsix

---

src/api/atelier.d.ts
src/providers/FileSystemProvider/TextSearchProvider.ts
src/utils/FileProviderUtil.ts
src/utils/index.ts

This PR fixes #849 and fixes #856
Changes made:
- Use `AtelierAPI.getDoc()` instead of `vscode.workspace.openTextDocument()` to get the document contents.
- Limit the number of documents being processed at once so the server doesn’t get overloaded.
- Check the `CancellationToken` and stop if the search was cancelled.
- Return correct line when `multilineMethodArgs` is set.
- Add better support for resolving a line from all class member/attribute combinations.
- Support multiple matches on a single line.
- Use the `filter` and `type` isfs query parameters to avoid searching files that the user doesn’t have in their folder.
- Return useful warning messages and properly log errors.
- Fix the type definition for `SearchMatch`.

Improve `TextSearchProvider`

---

package.json
src/utils/index.ts
syntaxes/vscode-objectscript-output.tmLanguage.json

This PR adds functionality to colorize the VSCode ObjectScript output window, including displaying different colors for:
- Successful compilation
- Errored compilation
- Individual errors ('ERROR:', etc. prefixes)
- ObjectScript authorization error
- Classes/routines/file names in compilation status
- Quoted strings, numbers, dates/times
Examples:

Colorize VSCode ObjectScript Output

---

images/fileIcon.svg
package.json

https://github.com/microsoft/vscode/issues/140047 adds the ability to provide default file icons for contributed languages. This PR adds the InterSystems logo as the default file icon for all of our contributed languages (classes, routines, includes and CSP/CSR). Unfortunately, the Salesforce cloud will still be the file icon for `.cls` files because it comes from the default [Seti file icon theme](https://github.com/jesseweed/seti-ui). Once this PR gets approved we should consider opening a PR in that repo that uses this icon for `.mac`, `.int`,  `.inc`, `.csp` and `.csr` files so nobody else beats us to them.
EDIT: I've included some screenshots below.
This is the current behavior:
This is with this PR using a dark theme:
This is with this PR using a light theme:

Add default file icons

---

src/providers/FileSystemProvider/TextSearchProvider.ts

This is preferable to using `AtelierAPI.getDoc()` because the latter always fetches the full content of the document, while the former invokes the `FileSystemProvider`'s `readFile()` method and therefore benefits from its caching functionality.

Use `vscode.workspace.fs.readFile()` in `TextSearchProvider`

---

src/providers/FileSystemProvider/FileSystemProvider.ts

This PR fixes #879
The recent work to support copying in isfs folders in VS Code Explorer broke ObjectScript Explorer's ability to open server-side files for editing when configured to do this.

Fix regression that broke server-side editing from ObjectScript Explorer

---

docs/SettingsReference.md
package.json
src/extension.ts

This PR fixes #876 
When `objectscript.openClassContracted` is `true`, automatically collapse all folding ranges when a class is opened for the first time.

Add `objectscript.openClassContracted` setting

---

README.md
docs/ReportingIssues.md
docs/index.md

This PR fixes #874 
I just copied the info from the README into a new page on the docs website. Should I remove it from the README as well so we don't need to maintain two copies? I'm indifferent.

Add `Reporting Issues` page to docs

---

src/api/index.ts

This PR fixes #853 
I modified the error handling so that `Non-JSON response` errors are treated the same as any other. This will eliminate the many non-helpful error messages that flood the Output channel.

Don't log `Non-JSON response` errors to the Output channel

---

docs/SettingsReference.md
package.json
src/explorer/models/classNode.ts
src/explorer/models/cspFileNode.ts
src/explorer/models/packageNode.ts
src/explorer/models/routineNode.ts
src/providers/DocumentContentProvider.ts

This PR fixes #494 
I verified that the explorer works properly with the new setting enabled or disabled, and that the LS's go to definition provider still opens the local copy of the file regardless of the new setting's value.

Add `objectscript.explorer.alwaysShowServerCopy` setting

---

src/providers/DocumentContentProvider.ts
src/providers/FileSystemProvider/TextSearchProvider.ts
src/utils/FileProviderUtil.ts

Previously the `TextSearchProvider` wouldn't work for csp folders because the generated URIs were malformed. This PR fixes that issue and changed the StudioOpenDialog file spec for the root csp folder from `*` to `*.cspall` so only files in csp directories are searched.

Fix `TextSearchProvider` for csp folders

---

src/api/index.ts
src/utils/index.ts

The purpose of this PR is to enable an upcoming PR of mine for https://github.com/grongierisc/iris-python-template which will allow VS Code to connect remotely to that container as an alternative to the original way of using VS Code with it.
This change will mean that any `docker-compose` element of a (usually workspace-specific) `objectscript.conn` will be ignored when the extension is running in a remote extension host. A suitably-structured `objectscript.conn` written into the container by the workspace's `devcontainer.json` will instead create a within-container connection.

Ignore `objectscript.conn.docker-compose` when running in dev container

---

src/api/index.ts
src/commands/compile.ts

This PR removes the use of the synchronous `/action/compile` API and instead uses the `/work` endpoints to compile documents. We've had reports internally of users running into `504 Gateway Timeout` errors when compiling a class took more than 60 seconds. While the users could increase the timeout, they could always run up against it again in the future. Using this approach ensures that the extension will not break, regardless of how long compilation on the server may take.
I'm leaving this as a draft until the people who ran into the gateway timeout issue internally verify that this works for them.

Compile asynchronously

---

docs/RunDebug.md
src/debug/debugSession.ts

Multiple issues have been raised in past about being unable to start debug sessions that turned out to be caused by the user's web server configuration (#607, #773, #830, #891). This PR adds a line in the documentation about the WebSocket requirement and improves the error when debugging fails to start.

Improve error message when debugging fails to start

---

package-lock.json
package.json
src/utils/index.ts

VS Code 1.66 was released and with it the `outputChannelLanguage` API was finalized. We should use the new finalized API so everyone will get their Output channel colorized.

Finalize `outputChannelLanguage` API

---

package.json

This PR fixes #911 
I reviewed the [VS Code docs for when clauses](https://code.visualstudio.com/api/references/when-clause-contexts#available-contexts) and this clause is true when the VS Code UI is running a browser, not the extension. We should remove this so the extension works as intended when it's installed in an environment like code-server.

Remove `isWeb` clauses from package.json

---

src/commands/compile.ts
src/extension.ts
src/utils/index.ts

This PR fixes #777
Whenever the connection is checked I cache the list of available web apps in a server-namespace and use this list to determine if a local non-CSP/CSR file can be imported as a web app file.

Fix importing of web app files

---

src/api/index.ts

See https://community.intersystems.com/post/vscode-objectscript-extension-trusting-self-signed-certificates#comment-186796

Correctly use `http.proxyStrictSSL` setting

---

src/extension.ts

This PR fixes uncaught errors that are reported in the VS Code extension view UI:
The errors are caused by the `onDidChangeActiveTextEditor()` handler for the  `openClassContracted` setting, which is trying to read the `document`, property of the `TextEditor` argument which may be `undefined`.

Fix uncaught errors

---

src/providers/FileSystemProvider/FileSystemProvider.ts

This PR fixes an issue with copying a class file overwriting inheritance. Previously, dragging an existing cls file into the project will overwrite existing inheritance code (... Extends %Persistent ...).

Fix issue with copying class file overwriting inheritance

---

src/commands/jumpToTagAndOffset.ts
src/extension.ts

This PR fixes #957 
Call the `vscode.executeDocumentSymbolProvider` command and use the symbols to determine label+offset for the status bar item.
***NOTE:*** This PR won't fix the issue until the next Language Server version is released due to a dependency on chnages to its `DocumentSymbolProvider`.

Use `DocumentSymbolProvider` for tag+offset status bar item

---

package.json
syntaxes/objectscript-class_codeblock.json
syntaxes/objectscript_codeblock.json

Prompted by https://community.intersystems.com/post/syntax-highlighting-vs-code-markdown
Implemented using information at https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example
Leverages the TextMate grammars which we fall back to when Language Server isn't available.
Coloring shows in the text as it is being edited, but unfortunately doesn't carry through to preview.
Markdown text for above example:
MAC or INT code example:
```objectscript
//create the object
set diagnosis=##class(MyApp.Clinical.PatDiagnosis).%New()
//set a couple of properties by using special variables
set diagnosis.Date=$SYSTEM.SYS.TimeStamp()
set diagnosis.EnteredBy=$username
set status=diagnosis.%Save()
//always check the returned status
if $$$ISERR(status) {do …
```

Support `objectscript` and `objectscript-class` in Markdown fenced codeblocks

---

src/commands/compile.ts
src/commands/export.ts
src/utils/index.ts

This PR fixes #952 
This replaces all calls to node's `fs` with vscode's `workspace.fs`, expect for the `DocumentContentProvider`, which appears to require the synchronous node APIs

Replace node `fs` with vscode `workspace.fs`

---

.github/workflows/codeql-analysis.yml

https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/

update codeql version

---

docs/SettingsReference.md
package.json

This PR should address the confusion some users have, as reported in the [Developer Community](https://community.intersystems.com/post/vscode-go-definition-opens-read-only-mode#comment-201811).

Improve docs for `objectscript.export.folder` setting

---

src/extension.ts

This PR fixes #989 
It minimally relaxes a previous constraint in the `serverForUri` API, allowing this function to return the password for a named server if that password is already available to every extension because of having been stored in settings.

Allow `serverForUri` API to return insecure password from `intersystems.servers` (#989)

---

docs/SettingsReference.md
package.json
src/providers/ObjectScriptCodeLensProvider.ts

* Fixes #996 
* Adds CodeLenses for INT routines
* Adds documentation for `objectscript.debug.copyToClipboard`
* Shortens debug CodeLens name from `Debug this method` to `Debug`

Improve CodeLenses

---

CHANGELOG.md
README.md
package-lock.json
package.json

See CHANGELOG for what is included.
@gjsjohnmurray Are we sticking with even minor versions even though there are no more prerelease versions?

Prepare 2.2.0 release

---

docs/SettingsReference.md
package.json
src/extension.ts
src/providers/FileDecorationProvider.ts

This PR fixes #987. I added a "gear" `FileDecoration` for generated files that appears once it has been opened. I also added a setting for turning them off for people (like me) who see this as UI clutter rather than a valuable feature.

Add `FileDecoration` for Generated files

---

src/commands/compile.ts
src/debug/debugSession.ts
src/utils/index.ts

Calling `openTextDocument` causes the Language Server to parse the document and report Diagnostics, which doesn't make sense since the those documents may never be shown in the UI. This PR removes those calls and uses `workspace.fs.readFile()` instead.

Don't call `openTextDocument` in debugger

---

.github/workflows/main.yml
.github/workflows/prerelease.yml

beta workflow failed when updating my fork:
"Unable to resolve action `softprops/action-gh-release@v0`, unable to find version `v0`"

Try to fix CI failure since #1050

---

src/commands/compile.ts
src/providers/FileSystemProvider/FileSystemProvider.ts
src/utils/index.ts

The Index API transfers a lot of data that is not needed to check if a class is deployed. It is much more efficient to query `%Dictionary.ClassDefinition` directly.

Use query instead of index for class Deployed checks

---

src/api/index.ts
src/commands/serverActions.ts
src/explorer/explorer.ts
src/extension.ts
src/providers/DocumentContentProvider.ts
src/providers/FileSystemProvider/FileSystemProvider.ts

This PR fixed #1049. `workspaceState` keys related to connection information are now stored in all lowercase to prevent misses based on key case. It also contains some small improvements:
* Fix error logging in `FileSystemProvider`.
* Log errors in `vscode-objectscript.explorer.open` to the Output channel.
* Replace calls to deprecated `url.parse()` method.

Use lowercase for workspace folder state connection keys

---

src/commands/serverActions.ts
src/utils/index.ts

This PR fixes #947 
I added a function that runs `docker compose version` and if the command doesn't error, `docker compose` is used as the command for compose features instead of the older `docker-compose`.

Use `docker compose` command if present

---

src/commands/compile.ts

This PR ensures that if a class/routine/etc was loaded read-only by another extension using an `objectscript://` uri, then if the user imports an updated copy of the same file (client-side or server-side development paradigm) the read-only document reloads.

Trigger reload of any `objectscript://` document after import

---

src/explorer/explorer.ts

This PR fixes #1068. I had to change the `stat()` call to `readFile()` because `readFile()` is allowed to create intermediate folders while `stat()` isn't.

Fix opening of `isfs` files from ObjectScript Explorer

---

src/commands/restDebugPanel.ts

This PR fixes #1078. It also improves error handling when the debuggee REST request couldn't be sent.

Support non-ASCII characters in REST Debug query params

---

src/commands/serverActions.ts

This PR adds a "Switch namespace" option to the server action menu. Triggering this will show a quick pick menu with all available namespaces in the server and will do the switch if user selects one. This functionality is useful when doing local development without server-side editing on a server that has multiple namespaces.

Add `Switch Namespace` option to Server Actions menu for local workspace folders

---

docs/Studio.md

I think this is clearer than using the Mac "Option" symbol since Studio users are coming from Windows.

Replace symbols with Alt in Studio keybindings table

---

src/commands/restDebugPanel.ts

This PR fixes #1091 
Generally, only `text/*` MIME types can contain the `charset` parameter but IRIS seems to respond to it for JSON so I added it for all types.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#structure_of_a_mime_type

Add charset to REST Debug panel's Content-Type

---

package.json
src/commands/jumpToTagAndOffset.ts
src/extension.ts

This PR fixes #1094 
The command is available in the command palette. When run, it prompts the user to enter an error location in the format `label+offset^routine`, then opens that location.

Implement `Open Error Location...` command

---

CHANGELOG.md
README.md
package.json

The next version is currently set for 2.4.4 but the change list is pretty big so if you want to bump it to 2.6.0 I can do that.

Prepare next release

---

docs/Configuration.md
src/commands/serverActions.ts

This PR adds the `SOAP Wizard` to the Server Actions menu. We get a lot of questions about this wizard so it makes sense that we should link to it without requiring user configuration. If the user already manually added a link to it using the `objectscript.conn.links` setting, their menu item will be shown instead of our default one.

Add `SOAP Wizard` to Server Actions menu

---

src/extension.ts

This PR stops the extension from forcibly switching the Panel to show our Output channel whenever activating with proposed APIs enabled.

Don't switch Panel to Output tab when starting with proposed API enabled

---

docs/ServerSide.md
docs/SettingsReference.md
package.json
src/extension.ts
src/providers/DocumentContentProvider.ts

Deprecate confusing `objectscript.serverSideEditing` setting

---

src/debug/debugSession.ts

This PR fixes #1136 by making debug's secure websocket check the same setting as the extension does for its REST requests over https to a webserver that uses a self-signed certificate.

Debugging's websocket should ignore self-signed cert error when `http.proxyStrictSSL` is `false`

---

src/extension.ts

This PR adds the jobs config name to the "Pick the process to attach to" menu items. This makes it easy to see and select the right Business Host to attach to. Without this, the user has to open the Management Portal, open the Production, select the Business Host and finally open the Jobs tab to see what the process pid is and then choose same pid in the "Pick the process to attach to" menu.

Show jobs config name in the attach to process debug menu

---

docs/SettingsReference.md
package.json
src/extension.ts

This PR adds a prompt to open the "Enable Proposed API" README directions when the workspace contains an `isfs` or `isfs-readonly` folder upon activation, or one is added.

Prompt user to enable proposed APIs if server-side folder is open

---

src/providers/FileSystemProvider/FileSystemProvider.ts

This PR fixes #1143 
In 2.8.0 an ISFS folder whose server was [configured to support folder-specific settings](https://intersystems-community.github.io/vscode-objectscript/serverside/#configuring-storage-for-folder-specific-settings) was ignoring its settings.
To verify, create an ISFS workspace, open a class or routine, and  add this folder-specific setting:
```json
{
"editor.fontSize": 24
}
```
Confirm that the font size increases. Then reload the workspace and confirm the code reloads at the larger size. Prior to this fix the reload would show standard-size font.

Make folder-specific settings for ISFS folder work again

---

docs/RunDebug.md
docs/SettingsReference.md
package.json
src/api/index.ts
src/commands/webSocketTerminal.ts
src/extension.ts

This PR adds support for for the new terminal endpoint added in Atelier API v7. It will be available in the next preview of IRIS 2023.2. See the new documentation included in this PR for how to start the terminal and what features it supports.

Add WebSocket Terminal support

---

package.json

Fix typo in Projects Explorer welcome text

---

package.json
src/commands/webSocketTerminal.ts
src/extension.ts

This PR fixes a bug with the command for launching a terminal. It also contributes launch buttons to namespaces in the Server Manager tree, and respects the `terminal.integrated.defaultLocation` setting.

Make WebSocket Terminal launchable from Command Palette and Server Manager tree

---

src/providers/DocumentContentProvider.ts

This setting was deprecated in #1116.

Remove `objectscript.serverSideEditing` setting

---

docs/Configuration.md
src/commands/serverActions.ts

Like PR #1157 this adds a variable which some Studio add-ins rely upon being available in the `User` queryparam.
To use it, append `&User=${username}` to the relevant `objectscript.conn.links` entry.

Support a ${username} variable in Server Actions Menu custom entries

---

package-lock.json
package.json
src/debug/dbgp.ts
src/debug/debugSession.ts

* Fixes #1169 by implementing workaround described in https://github.com/microsoft/vscode/issues/185785#issuecomment-1601337997
* Fixes #1170 
* For `attach` requests, wait for the target process to break before attempting to set breakpoints.
* De-emphasize stack frames with source code that isn't available (for example, system classes that art deployed) so they aren't auto-opened when the target breaks. (required VS Code version 1.80 and above due to https://github.com/microsoft/vscode/issues/184640)
* Implemented `stopOnEntry` property for non-CSP `attach` requests.
* Upgrade to `@vscode` versions of the debug adapter and debug protocol modules.
* Always send `detach` command for disconnect requests, regardless of request type.
* Properly run the target process for non-CSP `attach` …

Debugger improvements

---

docs/Studio.md
package.json
src/api/index.ts
src/commands/compile.ts
src/commands/export.ts
src/commands/project.ts
src/commands/restDebugPanel.ts
src/commands/studio.ts
src/extension.ts
src/providers/RuleEditorProvider.ts
src/utils/documentPicker.ts

This PR fixes #1158 
See the docs for how to use the new commands.

Support importing/exporting XML files

---

package.json

This PR implements #1204 
When used with a version of Server Manager containing https://github.com/intersystems-community/intersystems-servermanager/pull/207 the WebSocket Terminal button should only appear on namespaces of servers that are 2023.2 or greater.
When used with earlier Server Managers the button should continue to display on all servers' namespaces. As before, clicking it on a pre-2023.2 server will produce an error notification.

Hide WebSocket Terminal button on incompatible servers (requires Server Manager 3.4.2+)

---

src/extension.ts
src/providers/DocumentContentProvider.ts
src/providers/FileSystemProvider/TextSearchProvider.ts
src/utils/FileProviderUtil.ts

This PR removes the query parameters that were deprecated in #1165

Remove `flat` and `type` isfs query parameters

---

package-lock.json
src/providers/FileSystemProvider/FileSystemProvider.ts

If an isfs user only holds the out-of-the-box %Developer role they aren't able to access the %SYS namespace, which is the home of the webapp providing folder-specific settings storage. This scenario was producing a misleading message advising a SQL GRANT statement to be run. This PR improves the message to help identify the problem.

Improve message to help resolve scenario where isfs user lacks %DB_IRISSYS:READ

---

src/extension.ts
src/providers/ObjectScriptCodeLensProvider.ts

This PR fixes #1213, #1214, #1215

Fix some routine CodeLens issues

---

src/commands/newFile.ts
src/providers/FileSystemProvider/FileSystemProvider.ts

This PR fixes #1230. It also fixes a bug where new file content was getting overridden due to bad buffer to string conversion. I switched from `Buffer.toString()` to `new TextDecoder().decode()`.

Put link to editor in class comment when creating new BPL/DTL

---

package.json
src/commands/newFile.ts
src/extension.ts

Add command for creating a new KPI

---

src/explorer/models/projectRootNode.ts

Fix sorting of items in Projects Explorer

---

src/commands/serverActions.ts

Previously passed as $NAMESPACE but this only works for first page of a multi-page add-in such as the SOAP wizard.
This PR fixes #1249

Pass namespace differently to Studio add-in (fix #1249)

---

src/debug/debugSession.ts

Support setting data breakpoints on subsequent debug sessions (fix #1251)

---

src/providers/FileSystemProvider/FileSystemProvider.ts

Don't overwrite file name if the new name couldn't be determined

---

images/InterSystems.svg

Already in 1.84 Insiders the Activity Bar position can be changed from Side to Top. The SVG of the InterSystems logo that the ObjectScript Explorer contributes wasn't displaying properly because its ratio wasn't 1:1
This PR corrects that.
Before:
After:

Adjust activity bar icon to work correctly with upcoming 1.84 top-bar feature

---

package-lock.json
package.json
src/debug/dbgp.ts

The server generally tries to send one "line" of console output per WebSocket "packet" when debugging. However, in cases where an extreme amount of output is written to the console in a short amount of time , the server may send a 32K chunk of many "lines". Currently our debug adapter chokes on that huge packet and throws an error, and the debugger becomes out of sync with the server. This PR fixes that.

Improve handling of debugging WebSocket messages

---

src/commands/newFile.ts

The new KPI command added by #1237 wasn't generating a method stub that the Studio KPI wizard generated. This PR adds that stub to the generated content.

Add new method stub to KPI classes created via command

---

src/commands/newFile.ts

In the KPI command in the `New File...` menu, there's a QuickPick of server resources that can be used to secure the KPI. There was no option to select "no resource", so I added one as the first option.

Allow users to select no resource in new KPI command

---

src/providers/FileSystemProvider/FileSystemProvider.ts

This PR fixes #1265
Breakage was caused by #1253.
To verify, make sure you can create a new .cls file in an ISFS folder in VS Code Explorer view.

Fix new class creation, broken in 2.10.4

---

src/providers/FileSystemProvider/FileSystemProvider.ts

Keep file contents when copying class definition if "Class" line not found

---

src/providers/FileSystemProvider/TextSearchProvider.ts

Our `TextSearchProvider` assumes that the server won't send back junk results. This leads to it choking if it tries to process an invalid document name. This problem can arise due to a server-side bug described [here](https://github.com/intersystems-community/vscode-objectscript/issues/1273#issuecomment-1816587381). This PR hardens the code to ignore clearly invalid document names.

Harden `TextSearchProvider`

---

src/commands/webSocketTerminal.ts

Support home and end keys in WebSocket Terminal

---

package-lock.json
package.json
src/extension.ts
src/providers/FileSystemProvider/FileSystemProvider.ts

The current version of the plugin still has several unresolved issues that I have encountered, detailed as follows:
1. When openning server-side Classes using ObjectScript Explorer, pressing Ctrl+S and select a folder from the current workspace invariably prompts a question about overwriting. This happens because, upon file creation, the plugin automatically inserts a stub class code which often has a) an incorrect Package, and b) invariably triggers an overwrite prompt.
2. The issue of the Class file's Package being altered during movement persists in the latest version of the plugin. Every scenario I reported in my previous case still occurs.
3. When a file is a binary file but has a .cls extension, dragging it between folders in VSCode can corrupt its binary structure.
To thoroughly …

PR to fix my previous issues.

---

src/commands/webSocketTerminal.ts

The debugger prompts users to check their web server's settings if the debug session can't be started. We should do the same for the WebSocket Terminal.

Better message when WebSocket Terminal can't be started

---

src/providers/FileSystemProvider/TextSearchProvider.ts

Harden `TextSearchProvider` (again)

---

src/languageConfiguration.ts

This PR improves the behavior introduced by #761. The current implementation only works if there's a single space for indentation. See #1297 for motivation.

Improve auto-commenting of new lines following ObjectScript comments

---

package-lock.json
package.json
src/commands/compile.ts
src/providers/FileSystemProvider/TextSearchProvider.ts

This PR removed `glob` as a dependency, replacing it with `vscode.workspace.findFiles()`. `glob`is still a dev depedency.

Remove `glob` as a dependency

---

src/commands/newFile.ts

IRIS BI KPI classes can be tested by opening them as a web page. This PR adds a link that can be opened in a browser so the testing page is easily accessible.

Add testing link to new KPIs

---

src/commands/newFile.ts
src/extension.ts
src/providers/ObjectScriptCodeLensProvider.ts

See https://github.com/intersystems-community/vscode-objectscript/pull/1302#pullrequestreview-1835923180

Add CodeLenses for BPLs, DTLs, KPIs and Rules

---

package-lock.json
src/commands/compile.ts
src/commands/documaticPreviewPanel.ts
src/commands/studioMigration.ts
src/commands/unitTest.ts
src/extension.ts
src/languageConfiguration.ts
src/providers/FileDecorationProvider.ts
src/providers/FileSystemProvider/FileSystemProvider.ts
src/providers/ObjectScriptCodeLensProvider.ts
src/providers/RuleEditorProvider.ts
src/web-extension.ts

* Rolls back #1298
* Adds auto-closing of C-style block comments (e.g. typing `/*` automatically adds `*/`)
* Adds new `const`s for language ID's to improve code readability and maintainability

Improve language configuration

---

src/commands/project.ts
src/commands/studio.ts
src/commands/unitTest.ts
src/explorer/explorer.ts
src/explorer/models/projectNode.ts
src/providers/FileSystemProvider/FileSearchProvider.ts
src/providers/FileSystemProvider/FileSystemProvider.ts
src/providers/FileSystemProvider/TextSearchProvider.ts

This PR fixes #1312
I think this is the best I can do with "other" actions to approximate what happens when a file is opened via the Atelier GET /doc/ API. @gjsjohnmurray I'd really appreciate your review on this since since you're a server-side source control expert.

Fire source control hooks when creating/opening/editing/deleting projects

---

src/utils/FileProviderUtil.ts

Generated INT routines shouldn't have their last dotted piece before the extension (e.g. the `1` in `User.Test.1.int`) split into a folder.

Better handling of generated INT routines in project folders

---

src/commands/unitTest.ts
src/providers/FileSystemProvider/FileSearchProvider.ts
src/providers/FileSystemProvider/TextSearchProvider.ts

I've reduced the `OpenedDocument` calls to what I consider the bare minimum (when expanding the root of a project ISFS folder, expanding a root of the Projects Explorer, or modifying a project). See https://github.com/intersystems-community/vscode-objectscript/issues/1312#issuecomment-1954709482 for motivation.

Reduce firing of `OpenedDocument` action for projects

---

package.json
src/commands/jumpToTagAndOffset.ts

This PR fixes #1323
I modified the `QuickPick` to update the text box if the user presses "Enter" and the text doesn't correspond to the currently selected `QuickPickItem`. This allows the user to use the text box to filter the options, then use the up and down arrows to select a label and gives them the opportunity to type an offset if they want. The downside is that two presses of "Enter" are required to select an option of you don't want to provide an offset (one to update the text, one more to confirm "no offset"). Here's a gif:

Improve `Jump to Tag + Offset` UI

---

package.json
src/commands/project.ts
src/extension.ts

This PR fixes #1324
I added a command called `Modify Project Metadata...`. It can be accessed from: 
* Projects Explorer (right-click on a project node)
* file explorer (right-click on server-side root folder with a `project` query parameter)
* command palette.
Right now the command only lets you change the Description of a project, but I chose a generic name in case we eventually want it to edit other properties (which I consider very unlikely).

Add `Modify Project Metadata...` command

---

src/commands/studio.ts

This PR fixes #1328 
@gjsjohnmurray @isc-rsingh Should I do any input validation on the VS Code side before attempting the `openExternal()`? That failing should be harmless since it's a Thenable and we aren't awaiting it. I doubt a Studio extension page is going to have links to spam web pages.

Support opening links from Studio extension pages

---

src/commands/studio.ts

Fixes an issue reported by a Deltanji user, caused by the project-level source control calls added in 2.12.2.
The setting previously added to allow Deltanji sites to suppress user action calls was not being respected.

Source control useractions for projects ignored `"objectscript.serverSourceControl.disableOtherActionTriggers": true` setting

---

package.json
src/extension.ts

This setting is no longer required because this extension depends on the Server Manager in its package.json

Remove `objectscript.ignoreInstallServerManager` setting

---

src/commands/unitTest.ts

Remove methods that no longer exist when updating test methods

---

src/api/index.ts
src/commands/serverActions.ts

This PR fixes https://community.intersystems.com/post/vscode-connect-non-existing-namespace-unable-select-other-namespace

Allow changing namespace from Server Actions menu when connected to an invalid namespace

---

src/providers/FileSystemProvider/FileSystemProvider.ts
src/utils/FileProviderUtil.ts

Our `FileSystemProvider` currently only supports directory URIs that don't end with a slash (for example, `isfs://iris:USER/User` works but `isfs://iris:USER/User/` always returns no contents). This PR fixes that bug by removing the trailing slash during processing if it's present. This bug is most clearly seen when trying to open a file using `Ctrl-O`. The Simple File dialog is shown, and when you try to see the contents of a directory that you haven't already expanded in the File Explorer, you get no results.

Support trailing slash in `isfs` directory URIs

---

src/extension.ts
syntaxes/vscode-objectscript-output.tmLanguage.json

This PR fixes #1359 
If a connected server has a [`SystemMode`](https://docs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=RACS_SystemMode) value of `LIVE`, `TEST`, or `FAILOVER`, a message will be written to the Output channel. This ahppens upon extension activation, or if a new workspace folder is added.

Output message with SystemMode upon connection to server

---

src/providers/FileSystemProvider/FileSearchProvider.ts
src/providers/WorkspaceSymbolProvider.ts

- Now includes classes as well as class members
- Only shows results from classes actually in the isfs folder (respects query params, doesn’t show anything for csp folders)
- Shows results even if no query is specified
- Uses local URI if present for client-side editing
- Resolves location correctly for delimited identifiers
- Checks cancellation token

`WorkspaceSymbolProvider` improvements

---

src/extension.ts
src/utils/index.ts

This PR fixes #1371 and fixes #1364
This change will make the extension fall back to the pre-#1351 behavior if the unauthenticated access fails.

Allow prompt for username if unauthenticated access fails

---

src/api/index.ts

By standard header name should be `if-none-match` not `if_none_match`
This PR fixes #1383

fixed header name

---

src/providers/WorkspaceSymbolProvider.ts

This is needed because the LIKE predicate uses the the same collation type as the column it matches against, and the %Dictionary Name columns use [EXACT collation](https://docs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=GSQL_collation#GSQL_collation_types) by default.

`WorkspaceSymbolProvider` should match case-insensitively

---

src/commands/compile.ts
src/commands/export.ts

This PR addresses some confusing behavior reported by an internal dev. They had a multi-root workspace connected to %SYS and USER on the same server. They had a document from %SYS in the active editor tab, but wanted to import an XML file into USER. The command defaulted to use the %SYS connection, so the file got imported into the wrong namespace. I think it's a better user experience to always ask for the connection if you're in a multi-root workspace.

XML Import/Export commands shouldn't assume a server connection in a multi-root workspace

---

package.json
src/commands/compile.ts
src/extension.ts
src/providers/FileSystemProvider/FileSystemProvider.ts
src/utils/FileProviderUtil.ts

* Fixes #1388 
* Fixes a bug in folder deletion in Project server-side workspace folders
* Improve performance of loading post-compile changes by reducing REST request volume
* Remove outdated code in `updateOthers()`

Add `Compile` command to server-side file explorer

---

package.json

Almost all of the commands that we contribute to the file explorer context menu are only apply to a single item. Therefore, it's confusing if the menu options appear when multiple items are selected since the user may not be able to tell which item the command is run with. I propose that we just hide the menu options of mulitselect is active.

Hide file explorer context commands when multiple items are selected

---

src/extension.ts

I think this was caused by a server-side change that HTML-encoded the quote characters in the error text.

Don't log error when attempting a debug attach in a non-Interoperability namespace

---

src/commands/studio.ts
src/extension.ts

This PR fixes a bug reported by an internal developer related to the firing of the `AttemptedEdit` source control action. The developer reported that after reverting a file in the source control UI (not VS Code) when VS Code refreshed its copy of the file the `AttemptedEdit` action was incorrectly fired, and then upon the next edit to the file the action was not fired. I determined that this was due to the `suppressEditListenerMap` that was added to avoid firing the action when the file was reverted by the the source control hook. I fixed this issue by changing the criteria that were checked before firing the action so the map was no longer needed.

Improve triggering of `AttemptedEdit` source control action

---

src/commands/compile.ts

* Fixes a bug where file bytes couldn't be converted to text due to an undefined instantiated variable
* Allows importing over a deployed class, which is consistent with the XML import command, and SMP, terminal, and Studio imports

Fix `Import Local Files...` command

---

src/extension.ts
src/providers/ObjectScriptCodeLensProvider.ts

This PR fixes #1392. I removed the `CSPCHD` token fetching code because we should let the browser handle the cookies.

Use default web application for CodeLens links

---

package.json
src/debug/debugSession.ts
src/debug/xdebugConnection.ts

This PR fixes #1375.
Marking as draft until a publicly available kit supports this change.

 Support command stepping in debugger

---

package.json
src/api/index.ts
src/extension.ts
src/utils/documentPicker.ts
src/utils/index.ts

This PR fixes #1379. The new `Open InterSystems Document...` command can be opened from the command palette and it provides a UI for browsing all files in the connected server-namespace. The user can either pick an item in the list, or type text into the filter box and press "Enter" to submit that. The UI should function very similarity to the built-in simple file dialog. I would like to assign a keybinding to this command, but I couldn't find a good one so I'm open to suggestions.

Add command for opening InterSystems documents

---

package.json
src/providers/FileSystemProvider/File.ts
src/providers/FileSystemProvider/FileSystemProvider.ts

This PR closes #1397
In some circumstances the current VS Code (1.91.1) doesn't correctly switch an editor to be readonly. My PR https://github.com/microsoft/vscode/pull/221023 will resolve this. Meanwhile I am creating this PR as a Draft.

Set file readonly if class is deployed or if server-side source control reports it not editable

---

package-lock.json
src/commands/serverActions.ts

Per https://docs.intersystems.com/ens201817/csp/docbook/DocBook.UI.Page.cls?KEY=GSTD_Templates#GSTD_template_arch a Studio add-in may expect `Project` and `User` in its %request object.

Provide Project and User parameters to Studio add-ins

---

src/commands/project.ts
src/utils/FileProviderUtil.ts

This PR fixes #1406 and fixes #1407

Fix showing of CSP files in project folders

---

src/extension.ts

Debug Attach: fix process picker error

---

package.json
src/debug/debugSession.ts

Always stop the debug target process when attaching

---

src/extension.ts

This PR fixes two issues affecting our panels in the status bar.
1. If a multiroot workspace has documents open from two servers, clicking between the tabs wasn't updating the connection details on the status bar.
2. If MAC or INT documents were open, the line reference panel on the status bar would sometimes be uexpectedly empty. One case was when the workspace initially reloaded and output was displayed on the Output tab of the Panel.

Improve reliability of updating status bar panels

---

package.json
src/debug/debugAdapterFactory.ts
src/debug/debugSession.ts
src/extension.ts

This PR implements some improvements to the type of debugging in which you attach to a running process on a server.
It adds an entry to "initialConfigurations" in package.json so users setting up debugging in a workspace or folder for the first time won't have to add an attach-type configuration manually.
It also makes attach-type debugging usable when no documents are open from the server. In this case, if the workspace is multi-root the user must select a folder before being offered the process picker.
In conjunction with the new "always pause the attached process" behaviour (#1415) this means it is no longer necessary to open a document from the target namespace before being able to attach and debug a running process.

Improvements to attach-type debugging

---

src/extension.ts

Fire source control hooks for opened and closed documents

---

src/commands/serverActions.ts

The Studio add-in that is integral to George James Software's Yuzinji tool misbehaves when invoked from VS Code.
This PR corrects the issue by adding CSPSHARE=1 to the URL with which an add-in is launched.
Based on commit https://github.com/intersystems-community/vscode-objectscript/pull/756/commits/f58416c6719b0f75bede71ed58240227bf8160f2 by @timleavitt which was part of PR #756 I think it's very likely Studio adds this parameter too, which would explain the problem which this PR fixes.

Add CSPSHARE=1 to align add-in behaviour with Studio

---

package-lock.json
package.json
src/api/index.ts

This PR fixes #1428
VS Code 1.93 adopted a version of vscode-proxy-agent that fixed a failure to pass-through the keepAlive option (see https://github.com/microsoft/vscode/issues/173861 and https://github.com/microsoft/vscode-proxy-agent/commit/4eddc930d4fbc6b88ca5557ea7af07d623d390d6).
This caused poor performance on some operations by our extension (see #1428 and others linked there).
Short term solution adopted by this PR is not to enable keepAlive. We should revisit this in the future.

Solve 1.93 performance issue

---

.github/workflows/main.yml
.github/workflows/prerelease.yml

```
Unable to download artifact(s): Artifact not found for name: meta
Please ensure that your artifact is not expired and the artifact was uploaded using a compatible version of toolkit/upload-artifact.
For more information, visit the GitHub Artifacts FAQ: https://github.com/actions/toolkit/blob/main/packages/artifact/docs/faq.md
```
See also https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#multiple-uploads-to-the-same-named-artifact

Try to fix CI failure caused by non-unique name (meta) passed to download-artifact

---

src/providers/FileSystemProvider/FileSearchProvider.ts

This PR fixes #1443 which occurs on VS Code 1.94+
A separate issue is that the Explorer Find widget now depends on FileSearchProvider. I will raise this with the VS Code project.

Make Explorer Find widget work in 1.94 as long as proposed APIs are enabled (fix #1443)

---

src/providers/FileSystemProvider/FileSearchProvider.ts

This PR fixes #1445.
Still investigating some match failures, which may be caused by a VS Code bug. Hence PR is initially Draft.

Fix fuzzy match in Explorer tree Find on an ISFS folder in 1.94 (fix #1445)

---

src/commands/webSocketTerminal.ts

This PR fixes #1450. It also adds support for adjusting the text when the terminal window changes size.

Support for line wrapping in Lite Terminal

---

package-lock.json
package.json
src/api/index.ts
src/commands/restDebugPanel.ts
src/extension.ts
src/providers/FileSystemProvider/FileSystemProvider.ts
src/providers/FileSystemProvider/TextSearchProvider.ts

This PR adds a 5 second timeout to connection requests made during extension activation to avoid a very long hang during activation if a server takes a long time to respond. I also migrated from `node-fetch` to `axios` to bring this extension in line with our other two. This is still blocked by https://github.com/microsoft/vscode/issues/227805.

Add timeout to initial connection request

---

package-lock.json
package.json
src/extension.ts
src/providers/FileSystemProvider/FileSystemProvider.ts

This PR leverages https://github.com/intersystems-community/intersystems-servermanager/pull/243
Requires Server Manager 3.8.0 in order to be effective, but shouldn't break when used with earlier version

Prevent overprompting for permission and account

---

src/providers/DocumentContentProvider.ts
src/utils/index.ts

Give priority to folder-specific docker-compose.yml once again

---

package-lock.json
package.json
src/api/index.ts
src/commands/studio.ts
src/test/suite/index.ts

This PR fixes #1460. The new `objectscript.outputRESTTraffic` setting supersedes the `objectscript.studioActionDebugOutput` setting. An example log output can be found below. I also had to make some test changes to address build failures.
```
+- REQUEST - 2:44:07 PM ----------------------------
GET http://localhost:52773/iris/api/atelier/
COOKIE: <value>
ACCEPT: application/json
CACHE-CONTROL: no-cache
AUTHORIZATION: <value>
+- RESPONSE - 2:44:07 PM ---------------------------
200 OK
DATE: Wed, 22 Jan 2025 19:44:07 GMT
SERVER: Apache/2.4.59 (Unix)
SET-COOKIE: <value>
CACHE-CONTROL: no-cache
EXPIRES: Thu, 29 Oct 1998 17:04:19 GMT
PRAGMA: no-cache
CONTENT-LENGTH: 395
CONNECTION: close
CONTENT-TYPE: application/json; charset=utf-8
Body:
{
"status": {
"errors": [],
"summary": ""
},
"console": …
```

Add a setting for logging REST traffic

---

src/commands/webSocketTerminal.ts

This PR fixes #1472
Test Lite Terminal launching from both Command Palette and Terminal view in the following cases:
1. No eligible connections in the workspace.
2. More than one eligible connection but user presses Esc on selector.

Better messaging (or not) when Lite Terminal launch is aborted (fix #1472)

---

package.json
src/commands/addServerNamespaceToWorkspace.ts

Permit `Modify Server-side Workspace Folder...` before connection becomes active

---

src/api/index.ts
src/extension.ts
src/utils/index.ts

This PR enables an incoming Server Manager enhancement to implement https://github.com/intersystems-community/intersystems-servermanager/issues/187
The VSIX built from this PR should work OK with Server Manager VSIXes that don't contain the relevant change, and vice versa. However the new features will only become available when both extensions have been updated.

Support Server Manager being able to handle `objectscript.conn.docker-compose` type connections

---

src/commands/restDebugPanel.ts

This PR fixes #1482. The original design of the webview made a false assumption that the web application definition would always be in the same namespace as the code being debugged. By removing the dropdown, that restriction has been lifted.

Don't restrict REST debug webview to web apps in the current namespace

---

package.json
src/api/index.ts
src/extension.ts
src/utils/index.ts

This PR closes #1243
It will make the recently added `asyncServerForUri` API function resolve a Docker container connection's local superserver port into `server.superserverPort`, allowing future development in other extensions such as Server Manager to identify the superserver port of container-type connections as well as for ordinary ones.

Extend `objectscript.conn.docker-compose` settings object to handle superserver port identification

---

src/commands/addServerNamespaceToWorkspace.ts
src/commands/compile.ts
src/commands/export.ts
src/commands/newFile.ts
src/extension.ts
src/utils/index.ts

- More info than built-in `showWorkspaceFolderPick()`.
- Allows for filtering invalid folders before prompting the user.
- Will not prompt the user if there is only one folder to pick from.
- Differentiates between user cancel and nothing to pick from.

Implement custom workspace folder picker

---

src/commands/addServerNamespaceToWorkspace.ts
src/commands/compile.ts
src/commands/connectFolderToServerNamespace.ts
src/commands/export.ts
src/commands/jumpToTagAndOffset.ts
src/commands/project.ts
src/commands/serverActions.ts
src/commands/studio.ts
src/commands/subclass.ts
src/commands/superclass.ts
src/commands/unitTest.ts
src/commands/xmlToUdl.ts
src/explorer/explorer.ts
src/extension.ts
src/utils/index.ts

* Use `title` instead of `placeHolder` for inputs that only have one prompt
* Normalize language
I deliberately didn't do anything about `ignoreFocusOut` because I wanted to get your feedback first. Should we remove this from our extensions so there's always a mouse option to dismiss an input? Once this PR is merged I will make similar changes to the other two extensions.

Input UI normalization

---

src/extension.ts
src/providers/ObjectScriptCodeLensProvider.ts

This is an improvement because it guarantees that our custom editor is opened when users click the `Reopen in Low-Code Editor` CodeLens. The command we were using before could open a different custom editor if another extension offered one for `.cls` files.

Implement custom command for opening Low Code editors

---

.vscodeignore
src/commands/documaticPreviewPanel.ts
src/commands/restDebugPanel.ts
src/commands/showPlanPanel.ts
src/commands/viewOthers.ts
src/extension.ts
src/providers/ObjectScriptCodeLensProvider.ts
src/utils/index.ts

This PR adds a new `Show Plan` CodeLens. The CodeLens will appear above `%SQLQuery` Class Query definitions and Embedded SQL queries if the query can generate an execution plan, and a connection to IRIS 2024.1+ is active. When the CodeLens is clicked, the query text, select mode and imported packages are extracted from the document and sent to the server. The returned plan is then rendered as HTML in a webview. Only one Show Plan webview can be visible at any time. Include files are captured, and support for passing them to the server-side SQL plan code will come in a future IRIS release.

Implement `Show Plan` CodeLens

---

src/commands/webSocketTerminal.ts

* Set the `IsWindows` [property](https://code.visualstudio.com/docs/terminal/shell-integration#_vs-code-custom-sequences-osc-633-st) to `False`
* Re-order shell integration sequences (https://github.com/microsoft/vscode/issues/242897)

Improve Lite Terminal shell integration

---

src/commands/compile.ts
src/commands/export.ts
src/utils/index.ts

This PR fixes #1508. I tested this with a local folder that didn't exist and verified that the OS file explorer dialog is still shown.

Remember last used local folder for server-side import/export

---

src/providers/ObjectScriptCodeLensProvider.ts

This PR improves #1503 in the following ways:
* `Debug` CodeLens appears before `Copy Invocation` in class definitions again.
* Improves the detection of subroutines/procedures that are publicly available and therefore can be debugged.

Improve #1503

---

package.json
src/commands/compile.ts
src/commands/export.ts
src/commands/newFile.ts
src/commands/xmlToUdl.ts
src/extension.ts
src/utils/documentIndex.ts
src/utils/index.ts

This PR fixes an issue reported on [the Developer Community](https://community.intersystems.com/post/do-you-use-client-side-editing-vs-code-if-so-we-want-your-feedback#comment-280079). The `objectscript.syncLocalChanges` setting is now an `enum` instead of a `boolean`. The `"all"` value corresponds to the previous `true` value, `"none"` corresponds to `false`, and `"vscodeOnly"` restores the pre-#1401 behavior.

Support only syncing local changes made form VS Code

---

src/utils/documentIndex.ts

This PR fixes an issue reported by an ISC employee. They has a `.code-workspace` file with multiple local folders. One of them was a subfolder of another. When they saved a file in the subfolder, two file change events were triggered, one for each workspace folder. This caused a loop when the file would keep being synced to the server and compiled. I fixed the issue by checking that the uri of the file event is actually in the workspace folder before I try to sync the changes.

Fix compile loop when one local workspace folder is a subfolder of another

---

CHANGELOG.md
README.md
src/commands/compile.ts
src/extension.ts

This PR fixes #1522. The issue is that we "recreate" the file when loading changes from the compiler, so Undo undoes this "creation" and deletes the file. I fixed the issue by going back to the `fs.writeFile()` API. This issue is pretty bad, so I'm considering bumping version as part of the PR and doing the 3.0.1 release immediately.

Fix issue where `Undo` after a save deletes the file being edited

---

package.json
src/api/index.ts
src/commands/compile.ts
src/commands/export.ts
src/providers/DocumentContentProvider.ts
src/providers/FileSystemProvider/FileSystemProvider.ts

Allow `objectscript.multilineMethodArgs` to be set per workspace folder

---

src/providers/FileSystemProvider/FileSystemProvider.ts

See https://github.com/intersystems-community/intersystems-servermanager/issues/266 and https://community.intersystems.com/post/sourcecontrol-errors

Show error message when a server-side file fails to open

---

src/commands/compile.ts

This PR fixes #1537. Note that this PR only addresses the issue for client-side editing workflows. The server-side work is much more involved and therefore should be done separately.

Update text of all local files changed by compilation

---

src/utils/documentIndex.ts

This PR fixes #1526. I don't know why these events are occurring, but this change will stop the issue they cause.

Ignore duplicate file change events in local workspace folders

---

src/commands/export.ts

This issue was reported internally.

Export namespace warning check should be case-insensitive

---

src/commands/project.ts
src/extension.ts
src/providers/FileSystemProvider/FileSystemProvider.ts

This PR was prompted by my investigation into #1523.
- Don't call `GET /api/atelier/` every tie we try to read the root folder.
- Only call the `OpenedDocument` UserAction once per workspace folder.

Reduce REST traffic for server-side folders

---

package.json
src/providers/FileSystemProvider/FileSystemProvider.ts

Show server-side source control menus when right-clicking on a project workspace folder root

---

package.json
src/commands/compile.ts
src/commands/studio.ts
src/providers/FileSystemProvider/FileSystemProvider.ts
src/providers/LowCodeEditorProvider.ts
src/utils/documentIndex.ts
src/utils/index.ts

This PR arose during my investigation of #1537 for server-side editing.
- Fire file change events for related documents that were updated by compilation.
- Remove unneeded cache clearing before firing file change events and refresh of server-side class that's open in a low-code editor. VS Code's calling of `stat()` will cause the file to update in these cases.
- Remove unneeded `workspaceState` updates from FileSystemProvider. This is a client-side feature.
- Fire file create events when creating files via `writeFile()`or `rename()`.
- Don't allow `rename()` to overwrite a file that's marked read-only by source control or due to being deployed.
- Don't allow using client-side "import and compile" commands with server-side files.
- Hide some commands when the active text editor is dirty. …

Small tweaks

---

src/commands/newFile.ts

This PR fixes #1535. Instead of showing the save dialog, I show an input box that allows the user to edit the path as a string. This enables the easy creation of intermediate directories that don't exist. There's still an option to open the save dialog, and the default path is still generated using the export settings.

Improve UI for selecting the URI of a new local class created via command

---

src/commands/xmlToUdl.ts

Show an error if the API is not active when selecting "Preview XML as UDL" on a file that is not connected to the remote server.

Show error message when `Preview XML as UDL` is run without an active server connection

---

syntaxes/objectscript.tmLanguage.json

This PR implements the suggested fix from https://github.com/microsoft/vscode/issues/248823#issuecomment-2883653569. This will not affect the semantic token-based coloring provided by the Language Server.

Improve bracket pair colorization of Embedded SQL

---

src/utils/documentIndex.ts

See comment in code for reasoning

Don't report error when deleting a local file that doesn't exist on the server

---

src/extension.ts

Fix `objectscript.autoAdjustName` behavior with `Save As...`

---

src/commands/compile.ts
src/extension.ts
src/providers/FileSystemProvider/FileSystemProvider.ts

This should help alleviate confusion with client-side editing on Windows (#1531, #1550)

Attempt to use existing line endings when replacing a file's contents post-compile

---

src/api/index.ts
src/extension.ts

This PR fixes #1572. The timeout wasn't being respected because I wasn't passing it as an argument to the recursive `HEAD` request call that is used to fetch the cookies.

Fix timeout of connection requests on activation

---

src/api/index.ts

Fix saving and re-opening of server-side documents on VS Code 1.101.0

---

src/extension.ts

Make it more clear when a server connection failed due to a timeout

---

src/extension.ts

This PR fixes #1593. If this is approved then I will make a corresponding change in Language Server.

Retrieve password from Server Manager case-sensitively

---

src/commands/compile.ts

This PR fixes an [issue reported on the DC](https://community.intersystems.com/post/vscode-csp-compare-server-failed).

Fix comparing of local and server versions of web app files

---

package-lock.json
package.json
src/commands/serverActions.ts
src/commands/unitTest.ts
src/commands/webSocketTerminal.ts
src/debug/debugSession.ts
src/extension.ts
src/providers/LowCodeEditorProvider.ts
src/utils/documentIndex.ts

Currently this extension collects very little telemetry. Better telemetry will help InterSystems identity and prioritize enhancements that will make the most impact for our users. The top level bullet points correspond to telemetry events, and the second level corresponds to the properties sent for that event.
- `extensionActivated` Sent when extension is activated.
- `languageServerVersion` May be undefined.
- `serverManagerVersion`
- `config.explorer.alwaysShowServerCopy` These are all stringified booleans with the value of the corresponding setting.
- `config.autoAdjustName`
- `config.autoShowTerminal`
- `config.suppressCompileMessages`
- `config.suppressCompileErrorMessages`
- `config.autoPreviewXML`
- `config.showGeneratedFileDecorations`
- `config.showProposedApiPrompt`
- …

Better telemetry

---

src/commands/webSocketTerminal.ts

Users should see no change in behavior

Remove `_api` property from Lite Terminal implementation

---

src/commands/webSocketTerminal.ts
src/extension.ts

This PR addresses part of https://github.com/intersystems-community/intersystems-servermanager/issues/284

Support servers defined at the workspace-folder level for launching Lite Terminal from Servers tree view

---

package.json
src/commands/connectFolderToServerNamespace.ts
src/utils/index.ts

This PR fixes uncaught errors reported by telemetry. Given the amount of redaction in the error stacks I can't test that the errors have been fixed. However, all of these code changes are small so I think this is safe to merge.

Fix uncaught errors reported by telemetry

---

src/extension.ts
src/utils/index.ts

Since `objectscript(xml)://` URIs are not in a workspace folder, resolving server connection information for them didn't always work. This lead to issues like a lack of intellisense in those files or the server connection for the current workspace being forced inactive. This also caused Language Server to prompt for a password when not necessary because this extension would not return the password when it was defined in plain text.

Fix resolving of server connection for files opened from InterSystems Explorer or XML preview

---

package.json
src/api/index.ts
src/commands/addServerNamespaceToWorkspace.ts
src/commands/connectFolderToServerNamespace.ts
src/extension.ts

- Changes to `Connect Folder to Server Namespace...` command:
- Allow selecting servers defined at the workspace folder level.
- Allow setting `objectscript.conn` at the workspace file or workspace folder level if the workspace file contains only one folder.
- Add `when` clause to `package.json` so command only shows up when it's valid to use it.
- Improve resolving of credentials for server definition that does not contain a username.

Better support for server definitions defined at the workspace folder level

---

package.json
src/commands/unitTest.ts
src/extension.ts

Currently an ISFS-type workspace that wants to use my InterSystems Testing Manager extension also gets a superfluous root entry in the Test Explorer from this extension.
The new setting will allow this to be turned off at a per-workspace level or above.

Add `objectscript.unitTest.enabled` setting for better coexistence with other testing extensions

---

src/utils/index.ts

Users have seen `AggregateError` written to he Output channel, but without the inner errors this is useless. This PR adds the inner errors to the stringified representation of `AggregateError`s.

Fully stringify `AggregateError` when writing to the Output channel

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

I think these will help users report better issues

Create GitHub issue templates

---

src/commands/export.ts
src/explorer/nodes.ts

Inspired by the `Servers` tree, we now show items warning that a server connection is inactive or an error occurred when fetching children. In the error case, the tooltip contains the detailed error message.

Better error handling when expanding InterSystems and Projects Explorers

---

package-lock.json
package.json
src/commands/webSocketTerminal.ts

- Adopts https://github.com/microsoft/vscode/issues/190253 so commands can be re-run without user confirmation
- Allow pasting of multi-line content into `READ` prompts
- Work around VS Code bug to allow re-running of multi-line commands
- Correctly capture command output in shell integration
- Fix some edge cases where the cursor and text could get out of sync
I'm opening this as a draft even though the code is ready for review because I think it should be merged just before a 3.2.0 release. This PR bumps the minimum supported VS Code version to 1.104.0 which we probably don't want to get in a 3.0.7 release if we need one.

Lite Terminal shell integration improvements
